"use server";

/**
 * Queue server actions — internal bursary request creation.
 *
 * createInternalRequestAction:
 *   - ADMIN role required
 *   - Creates (or finds) a Profile for the parent
 *   - Creates an Application with isInternal=true, status=PRE_SUBMISSION
 *   - Creates an Invitation record (token auto-generated by the helper)
 *   - Sends the INVITATION email via Resend with ?token=<token>
 *   - Writes an audit log entry
 *   - Revalidates /queue
 *
 * Hardened in PR2 of the applicant invitation flow: the Supabase auth user
 * is created up front with `email_confirm: true` (silent invite) and rolled
 * back on any DB failure so we never leave an orphan `auth.users` row.
 */

import { randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { School } from "@prisma/client";
import { requireRole, Role } from "@/lib/auth/roles";
import { withAdminContext, type Tx } from "@/lib/db/prisma";
import { createAuditLog } from "@/lib/audit/log";
import { sendEmail } from "@/lib/email/send";
import { createSupabaseAdminClient } from "@/lib/auth/supabase-admin";
import { createProfile } from "@/lib/auth/create-profile";
import { getAppUrl } from "@/lib/app-url";
import { createInvitation } from "@/lib/db/queries/invitations";

// ─── Validation schema ────────────────────────────────────────────────────────

const InternalRequestSchema = z.object({
  parentEmail: z.string().email("A valid parent email address is required"),
  parentName: z.string().min(1, "Parent name is required").max(200),
  childName: z.string().min(1, "Child name is required").max(200),
  school: z.nativeEnum(School, {
    error: () => ({ message: "Please select a school" }),
  }),
  roundId: z.string().uuid("Please select an assessment round"),
  reason: z.string().max(500, "Reason must be 500 characters or fewer").optional(),
  entryYear: z.coerce
    .number()
    .int()
    .min(2020, "Entry year must be 2020 or later")
    .max(2040, "Entry year must be 2040 or earlier"),
});

// ─── Result type ──────────────────────────────────────────────────────────────

export interface InternalRequestResult {
  success: boolean;
  reference?: string;
  error?: string;
  fieldErrors?: Record<string, string[]>;
}

// ─── createInternalRequestAction ─────────────────────────────────────────────

export async function createInternalRequestAction(
  formData: FormData
): Promise<InternalRequestResult> {
  const user = await requireRole([Role.ADMIN]);

  const raw = {
    parentEmail: (formData.get("parentEmail") as string | null) ?? "",
    parentName: (formData.get("parentName") as string | null) ?? "",
    childName: (formData.get("childName") as string | null) ?? "",
    school: (formData.get("school") as string | null) ?? "",
    roundId: (formData.get("roundId") as string | null) ?? "",
    reason: (formData.get("reason") as string | null) ?? undefined,
    entryYear: (formData.get("entryYear") as string | null) ?? "",
  };

  const parsed = InternalRequestSchema.safeParse(raw);
  if (!parsed.success) {
    return {
      success: false,
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const { parentEmail, parentName, childName, school, roundId, reason, entryYear } =
    parsed.data;

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();

  type ProfileLite = {
    id: string;
    email: string;
    firstName: string | null;
    lastName: string | null;
  };

  // 1. Determine whether the parent already has a Profile + auth user.
  //    Lookups go outside any DB transaction so we don't hold a connection
  //    while we make Supabase round trips.
  let profile: ProfileLite | null;
  try {
    profile = await withAdminContext((tx) =>
      tx.profile.findUnique({
        where: { email: parentEmail },
        select: { id: true, email: true, firstName: true, lastName: true },
      })
    );
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to look up parent profile";
    console.error("[createInternalRequestAction] profile lookup:", err);
    return { success: false, error: message };
  }

  let createdAuthUserId: string | null = null;
  let isNewUser = false;

  if (!profile) {
    const nameParts = parentName.trim().split(/\s+/);
    const firstName = nameParts[0] ?? parentName;
    const lastName = nameParts.slice(1).join(" ") || null;

    // 2. Create the Supabase auth user silently (no system email — the
    //    branded Resend INVITATION email is the only one the parent gets).
    const tempPassword = randomBytes(24).toString("base64url");
    const { data: created, error: createError } =
      await supabase.auth.admin.createUser({
        email: parentEmail,
        password: tempPassword,
        email_confirm: true,
        app_metadata: { role: "APPLICANT" },
      });

    if (createError || !created?.user) {
      const message =
        createError?.message ?? "Failed to create parent account";
      console.error(
        "[createInternalRequestAction] createUser error:",
        createError
      );
      return { success: false, error: message };
    }

    createdAuthUserId = created.user.id;
    isNewUser = true;

    try {
      profile = await withAdminContext(async (tx) => {
        const profileResult = await createProfile(tx, {
          id: createdAuthUserId!,
          email: parentEmail,
          role: Role.APPLICANT,
          firstName,
          lastName: lastName ?? undefined,
        });
        if (!profileResult.success) {
          throw new Error(profileResult.error);
        }
        return {
          id: createdAuthUserId!,
          email: parentEmail,
          firstName,
          lastName,
        };
      });
    } catch (err) {
      // Roll back the auth user — we can't proceed without a Profile.
      await supabase.auth.admin.deleteUser(createdAuthUserId).catch((rollbackErr) => {
        console.error(
          "[createInternalRequestAction] auth rollback failed:",
          rollbackErr
        );
      });
      const message =
        err instanceof Error ? err.message : "Failed to create parent profile";
      console.error(
        "[createInternalRequestAction] profile upsert error:",
        err
      );
      return { success: false, error: message };
    }
  }

  // 3-5. Round lookup + reference + application + invitation in one tx.
  let result:
    | {
        ok: true;
        application: { id: string; reference: string };
        invitationId: string;
        invitationToken: string;
        round: { id: string; academicYear: string };
        expiresAt: Date;
      }
    | { ok: false; error: string };

  try {
    result = await withAdminContext(async (tx: Tx) => {
      const round = await tx.round.findUnique({
        where: { id: roundId },
        select: { id: true, academicYear: true, status: true },
      });

      if (!round) {
        return { ok: false as const, error: "Selected round not found." };
      }

      const refPrefix = `INT-${round.academicYear.replace("/", "-")}-`;
      const existing = await tx.application.count({
        where: { reference: { startsWith: refPrefix } },
      });
      const reference = `${refPrefix}${String(existing + 1).padStart(4, "0")}`;

      const application = await tx.application.create({
        data: {
          reference,
          roundId,
          leadApplicantId: profile!.id,
          school,
          childName,
          entryYear,
          isInternal: true,
          status: "PRE_SUBMISSION",
        },
        select: { id: true, reference: true },
      });

      const expiresAt = new Date();
      expiresAt.setDate(expiresAt.getDate() + 30);

      const invitation = await createInvitation(tx, {
        email: parentEmail,
        applicantName: parentName,
        childName,
        school,
        roundId,
        authUserId: profile!.id,
        createdBy: user.id,
        expiresAt,
      });

      return {
        ok: true as const,
        application,
        invitationId: invitation.id,
        invitationToken: invitation.token,
        round: { id: round.id, academicYear: round.academicYear },
        expiresAt,
      };
    });
  } catch (err) {
    // If we created a brand-new auth user as part of this request, roll it
    // back so the next attempt can re-provision cleanly.
    if (createdAuthUserId) {
      await supabase.auth.admin.deleteUser(createdAuthUserId).catch((rollbackErr) => {
        console.error(
          "[createInternalRequestAction] auth rollback failed:",
          rollbackErr
        );
      });
    }
    const message =
      err instanceof Error ? err.message : "Failed to create internal request";
    console.error("[createInternalRequestAction]", err);
    return { success: false, error: message };
  }

  if (!result.ok) {
    if (createdAuthUserId) {
      await supabase.auth.admin.deleteUser(createdAuthUserId).catch((rollbackErr) => {
        console.error(
          "[createInternalRequestAction] auth rollback failed:",
          rollbackErr
        );
      });
    }
    return { success: false, error: result.error };
  }

  const { application, invitationId, invitationToken, round, expiresAt } = result;

  // 6. Send the invitation email
  const schoolLabel = school === "TRINITY" ? "Trinity School" : "Whitgift School";
  const emailResult = await sendEmail(parentEmail, "INVITATION", {
    applicant_name: parentName,
    child_name: childName,
    school: schoolLabel,
    round_year: round.academicYear,
    registration_link: `${appUrl}/register?token=${invitationToken}`,
    deadline: expiresAt.toLocaleDateString("en-GB"),
  });

  if (!emailResult.success) {
    console.warn(
      `[internalRequest] INVITATION email failed for ${parentEmail}: ${emailResult.error}`
    );
  }

  // 7. Audit log
  await withAdminContext((tx) =>
    createAuditLog(tx, {
      userId: user.id,
      action: "INTERNAL_REQUEST_CREATED",
      entityType: "Application",
      entityId: application.id,
      context: `Internal bursary request created for ${childName} (${parentEmail})`,
      metadata: {
        reference: application.reference,
        school,
        roundId,
        entryYear,
        reason: reason ?? null,
        invitationId,
        authUserId: profile!.id,
        isNewUser,
        emailSent: emailResult.success,
        emailMessageId: emailResult.messageId ?? null,
      },
    })
  );

  revalidatePath("/queue");

  return { success: true, reference: application.reference };
}
