"use server";

/**
 * Server actions for invitation management.
 *
 * Mirrors the hardened staff invite pattern (`inviteStaffAction` in
 * `src/app/(admin)/users/actions.ts`):
 *
 *   1. Validate input.
 *   2. Create Supabase auth user up front with a throwaway password and
 *      `email_confirm: true` so Supabase does not fire its system invite
 *      OTP email.
 *   3. Inside one `withAdminContext(tx)` transaction, upsert the Profile,
 *      create the Invitation row (token auto-generated by the helper) and
 *      write the audit log.
 *   4. On any failure between steps 3a–3c, roll back the auth user so we
 *      never leave an orphan `auth.users` row.
 *   5. Send the branded Resend INVITATION email with the
 *      `?token=<token>` link as the registration URL.
 */

import { randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import {
  ApplicationContributorRole,
  ApplicationContributorStatus,
  InvitationStatus,
  School,
} from "@prisma/client";
import { requireRole, Role } from "@/lib/auth/roles";
import {
  createInvitation,
  generateInvitationToken,
  getActiveBursaryHolders,
} from "@/lib/db/queries/invitations";
import { createSupabaseAdminClient } from "@/lib/auth/supabase-admin";
import { createProfile } from "@/lib/auth/create-profile";
import { getAppUrl } from "@/lib/app-url";
import { sendEmail } from "@/lib/email/send";
import { withAdminContext } from "@/lib/db/prisma";
import { createAuditLog } from "@/lib/audit/log";
import { prepopulateReassessment, getPreviousYearApplication } from "@/lib/db/queries/reassessment";
import { ensurePrimaryContributor } from "@/lib/db/queries/contributors";

import { AUDIT_ACTIONS, AUDIT_ENTITY_TYPES } from "@/lib/audit/actions";

// ---------------------------------------------------------------------------
// Validation schema
// ---------------------------------------------------------------------------

const InvitationSchema = z.object({
  email: z.string().email("A valid email address is required"),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  childName: z.string().optional(),
  school: z.nativeEnum(School).optional(),
  roundId: z.string().uuid("An application round is required"),
});

// ---------------------------------------------------------------------------
// Result type
// ---------------------------------------------------------------------------

export interface InvitationActionResult {
  success: boolean;
  error?: string;
  fieldErrors?: Record<string, string[]>;
}

export interface BatchInviteResult {
  sent: number;
  failed: number;
  errors: string[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Composes a single-line applicant display name from the structured first /
 * last fields, falling back to the empty string.
 */
function composeApplicantName(
  firstName: string | undefined,
  lastName: string | undefined
): string {
  return [firstName, lastName].filter(Boolean).join(" ").trim();
}

function schoolLabel(school: School | undefined | null): string {
  if (!school) return "";
  return school === "TRINITY" ? "Trinity School" : "Whitgift School";
}

// ---------------------------------------------------------------------------
// createInvitationAction (hardened — mirrors inviteStaffAction)
// ---------------------------------------------------------------------------

export async function createInvitationAction(
  formData: FormData
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  const raw = {
    email: formData.get("email") as string,
    firstName: (formData.get("firstName") as string) || undefined,
    lastName: (formData.get("lastName") as string) || undefined,
    childName: (formData.get("childName") as string) || undefined,
    school: (formData.get("school") as string) || undefined,
    roundId: (formData.get("roundId") as string) || undefined,
  };

  const parsed = InvitationSchema.safeParse(raw);
  if (!parsed.success) {
    return {
      success: false,
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const { email, firstName, lastName, childName, school, roundId } =
    parsed.data;

  const effectiveApplicantName = composeApplicantName(firstName, lastName);

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();

  // 1. Create Supabase auth user silently. email_confirm: true suppresses
  //    the built-in OTP email — only the branded Resend message will reach
  //    the applicant.
  const tempPassword = randomBytes(24).toString("base64url");
  const { data: created, error: supabaseError } =
    await supabase.auth.admin.createUser({
      email,
      password: tempPassword,
      email_confirm: true,
      app_metadata: { role: "APPLICANT" },
    });

  if (supabaseError || !created?.user) {
    const message = supabaseError?.message ?? "Failed to create auth user";
    console.error("[invitations] createInvitationAction createUser error:", supabaseError);
    return { success: false, error: message };
  }
  const authUserId = created.user.id;

  // 2. Profile + Invitation + audit log under one admin context. Any throw
  //    rolls back the auth user.
  let invitationId: string;
  let invitationToken: string;
  let academicYear = "";
  try {
    const result = await withAdminContext(async (tx) => {
      const profile = await createProfile(tx, {
        id: authUserId,
        email,
        role: Role.APPLICANT,
        firstName,
        lastName,
      });
      if (!profile.success) {
        return { success: false as const, error: profile.error };
      }

      const inv = await createInvitation(tx, {
        email,
        firstName,
        lastName,
        childName,
        school,
        roundId,
        authUserId,
        createdBy: user.id,
        expiresAt,
      });

      let year = "";
      if (roundId) {
        const round = await tx.round.findUnique({
          where: { id: roundId },
          select: { academicYear: true },
        });
        year = round?.academicYear ?? "";
      }

      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.CREATE_INVITATION,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: inv.id,
        context: `Sent invitation to ${email}`,
        metadata: {
          email,
          roundId: roundId ?? null,
          authUserId,
        },
      });

      return {
        success: true as const,
        invitationId: inv.id,
        token: inv.token,
        academicYear: year,
      };
    });

    if (!result.success) {
      await supabase.auth.admin.deleteUser(authUserId).catch((err) => {
        console.error(
          "[invitations] createInvitationAction auth rollback failed:",
          err
        );
      });
      return {
        success: false,
        error: result.error ?? "Failed to create invitation",
      };
    }

    invitationId = result.invitationId;
    invitationToken = result.token;
    academicYear = result.academicYear;
  } catch (err) {
    await supabase.auth.admin.deleteUser(authUserId).catch((rollbackErr) => {
      console.error(
        "[invitations] createInvitationAction auth rollback failed:",
        rollbackErr
      );
    });
    const message =
      err instanceof Error ? err.message : "Failed to send invitation";
    console.error("[invitations] createInvitationAction error:", err);
    return { success: false, error: message };
  }

  // 3. Send branded INVITATION email. The email is now inside the rollback
  //    boundary (#5): a send failure would otherwise leave a PENDING orphan
  //    row + auth user that looks valid but whose token never reached the
  //    recipient. On failure we hard-roll-back — delete the invitation row,
  //    delete the auth user, and write a failure audit entry so the attempt
  //    stays visible — then surface a clear error to the admin.
  const emailResult = await sendEmail(email, "INVITATION", {
    applicant_name: effectiveApplicantName || email,
    child_name: childName ?? "",
    school: schoolLabel(school),
    round_year: academicYear,
    registration_link: `${appUrl}/register?token=${invitationToken}`,
    deadline: expiresAt.toLocaleDateString("en-GB"),
  });

  if (!emailResult.success) {
    console.error(
      "[invitations] createInvitationAction email error:",
      emailResult.error
    );

    // Roll back the just-created invitation row and record the failure.
    await withAdminContext(async (tx) => {
      await tx.invitation.delete({ where: { id: invitationId } }).catch((err) => {
        console.error(
          "[invitations] createInvitationAction invitation rollback failed:",
          err
        );
      });
      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.CREATE_INVITATION_FAILED,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: invitationId,
        context: `Invitation to ${email} rolled back — email failed to send`,
        metadata: {
          email,
          roundId: roundId ?? null,
          authUserId,
          emailError: emailResult.error ?? null,
        },
      });
    }).catch((err) => {
      console.error(
        "[invitations] createInvitationAction rollback tx failed:",
        err
      );
    });

    // Roll back the auth user so we never leave an orphan account behind.
    await supabase.auth.admin.deleteUser(authUserId).catch((err) => {
      console.error(
        "[invitations] createInvitationAction auth rollback failed:",
        err
      );
    });

    revalidatePath("/invitations");
    return {
      success: false,
      error: `Email failed to send. The invitation was rolled back — please try again. (${emailResult.error})`,
    };
  }

  void invitationId; // referenced for type completeness; used by audit log above

  revalidatePath("/invitations");
  return { success: true };
}

// ---------------------------------------------------------------------------
// Reassessment invite — shared hardened core
// ---------------------------------------------------------------------------

type EligibleHolder = Awaited<
  ReturnType<typeof getActiveBursaryHolders>
>[number];

/**
 * Provisions one re-assessment invitation for a single eligible bursary holder
 * with the same auth-user-up-front + rollback hardening as
 * `createInvitationAction`. Mutates `result` in place (increments `sent` /
 * `failed`, appends to `errors`). Shared by both the all-holders batch action
 * and the selective action so the auth-user / rollback logic lives in exactly
 * one place.
 */
async function sendReassessmentInviteForHolder(
  holder: EligibleHolder,
  ctx: {
    roundId: string;
    academicYear: string;
    userId: string;
    supabase: ReturnType<typeof createSupabaseAdminClient>;
    appUrl: string;
  },
  result: BatchInviteResult
): Promise<void> {
  const { roundId, academicYear, userId, supabase, appUrl } = ctx;
  const { email, firstName, lastName } = holder.leadApplicant;
  const applicantName =
    composeApplicantName(firstName ?? undefined, lastName ?? undefined) ||
    email;

  // Per-row auth-user provisioning.
  let authUserId: string | null = null;
  try {
    const tempPassword = randomBytes(24).toString("base64url");
    const { data: created, error: supabaseError } =
      await supabase.auth.admin.createUser({
        email,
        password: tempPassword,
        email_confirm: true,
        app_metadata: { role: "APPLICANT" },
      });

    if (supabaseError || !created?.user) {
      throw new Error(supabaseError?.message ?? "Failed to create auth user");
    }
    authUserId = created.user.id;

    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + 30);

    const txResult = await withAdminContext(async (tx) => {
      const profile = await createProfile(tx, {
        id: authUserId!,
        email,
        role: Role.APPLICANT,
        firstName: firstName ?? undefined,
        lastName: lastName ?? undefined,
      });
      if (!profile.success) {
        return { success: false as const, error: profile.error };
      }

      const invitation = await createInvitation(tx, {
        email,
        firstName: firstName ?? undefined,
        lastName: lastName ?? undefined,
        childName: holder.childName,
        school: holder.school,
        roundId,
        bursaryAccountId: holder.id,
        authUserId: authUserId!,
        createdBy: userId,
        expiresAt,
      });

      await createAuditLog(tx, {
        userId,
        action: AUDIT_ACTIONS.BATCH_REASSESSMENT_INVITE,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: invitation.id,
        context: `Sent reassessment invitation to ${email}`,
        metadata: {
          email,
          roundId,
          bursaryAccountId: holder.id,
          authUserId,
        },
      });

      return {
        success: true as const,
        invitationId: invitation.id,
        token: invitation.token,
        expiresAt,
      };
    });

    if (!txResult.success) {
      throw new Error(txResult.error ?? "Failed to create invitation");
    }

    // Send branded reassessment email
    const emailResult = await sendEmail(email, "REASSESSMENT", {
      applicant_name: applicantName,
      child_name: holder.childName,
      school: schoolLabel(holder.school),
      round_year: academicYear,
      registration_link: `${appUrl}/register?token=${txResult.token}`,
      deadline: txResult.expiresAt.toLocaleDateString("en-GB"),
    });

    if (emailResult.success) {
      result.sent++;
    } else {
      result.failed++;
      result.errors.push(`${email}: ${emailResult.error}`);
    }
  } catch (err) {
    // Roll back the auth user if we got that far.
    if (authUserId) {
      await supabase.auth.admin.deleteUser(authUserId).catch((rollbackErr) => {
        console.error(
          `[reassessment-invite] auth rollback failed for ${email}:`,
          rollbackErr
        );
      });
    }
    const message = err instanceof Error ? err.message : "Unknown error";
    result.failed++;
    result.errors.push(`${email}: ${message}`);
    console.error(`[reassessment-invite] Error for ${email}:`, err);
  }
}

/**
 * Loads the eligible (active, not-yet-invited) holders for a round plus the
 * round's academic year, then runs `sendReassessmentInviteForHolder` over the
 * provided holder list (already filtered/scoped by the caller). Centralises
 * the load, rate-limit delay and revalidation so both public actions share it.
 */
async function runReassessmentInvites(
  roundId: string,
  selectIds: string[] | null
): Promise<BatchInviteResult> {
  const user = await requireRole([Role.ADMIN]);

  const result: BatchInviteResult = { sent: 0, failed: 0, errors: [] };

  let eligible: EligibleHolder[] = [];
  let academicYear = "";
  try {
    const loaded = await withAdminContext(async (tx) => {
      const h = await getActiveBursaryHolders(tx, roundId);
      const round = await tx.round.findUnique({
        where: { id: roundId },
        select: { academicYear: true },
      });
      return { holders: h, academicYear: round?.academicYear ?? "" };
    });
    eligible = loaded.holders;
    academicYear = loaded.academicYear;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to load bursary holders";
    console.error("[reassessment-invite] Load error:", err);
    result.errors.push(message);
    return result;
  }

  // When a selection is supplied, filter to it — defensively ignoring any id
  // that is not currently eligible (already invited / inactive). When null,
  // invite all eligible holders (the legacy batch behaviour).
  const holders =
    selectIds === null
      ? eligible
      : eligible.filter((h) => selectIds.includes(h.id));

  if (holders.length === 0) {
    result.errors.push("No eligible holders selected");
    return result;
  }

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();
  const ctx = { roundId, academicYear, userId: user.id, supabase, appUrl };

  for (let i = 0; i < holders.length; i++) {
    await sendReassessmentInviteForHolder(holders[i], ctx, result);

    // Rate-limit delay between sends (100 ms), skip after last item
    if (i < holders.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }

  revalidatePath("/invitations");
  return result;
}

// ---------------------------------------------------------------------------
// batchReassessmentInviteAction (hardened — per-row auth-user rollback)
// ---------------------------------------------------------------------------

/**
 * Sends reassessment invitations to ALL active bursary holders that have not
 * yet been invited for the specified round. Thin wrapper over the shared
 * `runReassessmentInvites` core (selectIds = null → all eligible). Retained for
 * backwards compatibility; the selective action is preferred from the UI.
 */
export async function batchReassessmentInviteAction(
  roundId: string
): Promise<BatchInviteResult> {
  return runReassessmentInvites(roundId, null);
}

// ---------------------------------------------------------------------------
// reassessmentInviteSelectedAction (selective — staff pick the holders)
// ---------------------------------------------------------------------------

/**
 * Sends reassessment invitations to a STAFF-SELECTED subset of the active
 * bursary holders for a round. Each requested id is filtered against the
 * currently-eligible set, so an id that is not eligible (already invited /
 * inactive) is silently ignored — we never invite a holder that isn't a valid
 * re-assessment candidate. Shares the exact same hardened per-row provisioning
 * + rollback as the batch action.
 */
export async function reassessmentInviteSelectedAction(
  roundId: string,
  bursaryAccountIds: string[]
): Promise<BatchInviteResult> {
  const ids = Array.isArray(bursaryAccountIds) ? bursaryAccountIds : [];
  if (ids.length === 0) {
    return { sent: 0, failed: 0, errors: ["No eligible holders selected"] };
  }
  return runReassessmentInvites(roundId, ids);
}

// ---------------------------------------------------------------------------
// resendInvitationAction
// ---------------------------------------------------------------------------

/**
 * Regenerates the single-use token, resets the 30-day expiry, and re-sends
 * the branded INVITATION email. Only valid on PENDING rows.
 */
export async function resendInvitationAction(
  invitationId: string
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  if (!invitationId || typeof invitationId !== "string") {
    return { success: false, error: "Invalid invitation id." };
  }

  try {
    const invitation = await withAdminContext((tx) =>
      tx.invitation.findUnique({
        where: { id: invitationId },
        include: {
          round: { select: { academicYear: true } },
        },
      })
    );

    if (!invitation) {
      return { success: false, error: "Invitation not found." };
    }

    if (invitation.status !== InvitationStatus.PENDING) {
      return {
        success: false,
        error: "Only pending invitations can be resent.",
      };
    }

    const newToken = generateInvitationToken();
    const newExpiresAt = new Date();
    newExpiresAt.setDate(newExpiresAt.getDate() + 30);

    await withAdminContext(async (tx) => {
      await tx.invitation.update({
        where: { id: invitationId },
        data: {
          token: newToken,
          expiresAt: newExpiresAt,
        },
      });

      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.RESEND_INVITATION,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: invitationId,
        context: `Resent invitation to ${invitation.email}`,
        metadata: {
          email: invitation.email,
          expiresAt: newExpiresAt.toISOString(),
        },
      });
    });

    const appUrl = getAppUrl();
    const applicantName =
      composeApplicantName(
        invitation.firstName ?? undefined,
        invitation.lastName ?? undefined
      ) || invitation.email;

    const emailResult = await sendEmail(invitation.email, "INVITATION", {
      applicant_name: applicantName,
      child_name: invitation.childName ?? "",
      school: schoolLabel(invitation.school),
      round_year: invitation.round?.academicYear ?? "",
      registration_link: `${appUrl}/register?token=${newToken}`,
      deadline: newExpiresAt.toLocaleDateString("en-GB"),
    });

    if (!emailResult.success) {
      console.error(
        "[invitations] resendInvitationAction email error:",
        emailResult.error
      );
      return {
        success: false,
        error: `Token refreshed but email failed to send: ${emailResult.error}`,
      };
    }

    revalidatePath("/invitations");
    return { success: true };
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to resend invitation";
    console.error("[invitations] resendInvitationAction error:", err);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// revokeInvitationAction
// ---------------------------------------------------------------------------

/**
 * Marks a PENDING invitation as EXPIRED. If the invitation was never accepted
 * and we provisioned a Supabase auth user up front, soft-delete that auth
 * user so we don't leave a half-onboarded account behind.
 */
export async function revokeInvitationAction(
  invitationId: string
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  if (!invitationId || typeof invitationId !== "string") {
    return { success: false, error: "Invalid invitation id." };
  }

  try {
    const invitation = await withAdminContext((tx) =>
      tx.invitation.findUnique({ where: { id: invitationId } })
    );

    if (!invitation) {
      return { success: false, error: "Invitation not found." };
    }

    if (invitation.status !== InvitationStatus.PENDING) {
      return {
        success: false,
        error: "Only pending invitations can be revoked.",
      };
    }

    const shouldDeleteAuthUser =
      invitation.authUserId !== null && invitation.acceptedAt === null;

    await withAdminContext(async (tx) => {
      await tx.invitation.update({
        where: { id: invitationId },
        data: { status: InvitationStatus.EXPIRED },
      });

      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.REVOKE_INVITATION,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: invitationId,
        context: `Revoked invitation to ${invitation.email}`,
        metadata: {
          email: invitation.email,
          authUserId: invitation.authUserId,
          authUserDeleted: shouldDeleteAuthUser,
        },
      });
    });

    if (shouldDeleteAuthUser && invitation.authUserId) {
      const supabase = createSupabaseAdminClient();
      const { error: deleteError } = await supabase.auth.admin.deleteUser(
        invitation.authUserId
      );
      if (deleteError) {
        console.error(
          "[invitations] revokeInvitationAction auth deletion warning:",
          deleteError
        );
      }
    }

    revalidatePath("/invitations");
    return { success: true };
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to revoke invitation";
    console.error("[invitations] revokeInvitationAction error:", err);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// createReassessmentApplicationAction
// ---------------------------------------------------------------------------

const ReassessmentApplicationSchema = z.object({
  bursaryAccountId: z.string().uuid("A valid bursary account ID is required"),
  roundId: z.string().uuid("A valid round ID is required"),
});

export interface ReassessmentApplicationResult {
  success: boolean;
  applicationId?: string;
  error?: string;
}

/**
 * Creates a re-assessment application and pre-populates it with personal
 * section data from the previous year.
 *
 * Called after an applicant registers via a re-assessment invitation.
 * Links the application to the existing BursaryAccount with isReassessment: true.
 */
export async function createReassessmentApplicationAction(
  bursaryAccountId: string,
  roundId: string
): Promise<ReassessmentApplicationResult> {
  await requireRole([Role.ADMIN]);

  const parsed = ReassessmentApplicationSchema.safeParse({
    bursaryAccountId,
    roundId,
  });
  if (!parsed.success) {
    return {
      success: false,
      error: parsed.error.issues.map((i) => i.message).join("; "),
    };
  }

  try {
    const result = await withAdminContext(async (tx) => {
      // Load bursary account details
      const account = await tx.bursaryAccount.findUnique({
        where: { id: bursaryAccountId },
        include: { leadApplicant: true },
      });

      if (!account) {
        return { success: false as const, error: "Bursary account not found." };
      }

      // Generate reference
      const reference = `REA-${account.reference}-${roundId.slice(0, 8).toUpperCase()}`;

      // Create the re-assessment application
      const application = await tx.application.create({
        data: {
          reference,
          roundId,
          bursaryAccountId,
          leadApplicantId: account.leadApplicantId,
          school: account.school,
          childName: account.childName,
          childDob: account.childDob,
          entryYear: account.entryYear,
          entryYearGroup: account.entryYearGroup,
          isReassessment: true,
          status: "PRE_SUBMISSION",
        },
      });

      // Every application must have a PRIMARY contributor from creation so the
      // section write path can tag the owner (dual-parent foundation).
      await ensurePrimaryContributor(tx, application.id, account.leadApplicantId);

      // Pre-populate from the most recent previous year application
      const previous = await getPreviousYearApplication(tx, bursaryAccountId, roundId);
      if (previous) {
        await prepopulateReassessment(tx, application.id, previous.id);
      }

      await createAuditLog(tx, {
        action: AUDIT_ACTIONS.CREATE_REASSESSMENT_APPLICATION,
        entityType: AUDIT_ENTITY_TYPES.Application,
        entityId: application.id,
        context: `Re-assessment application created for ${account.childName}`,
        metadata: {
          bursaryAccountId,
          roundId,
          previousApplicationId: previous?.id ?? null,
        },
      });

      return { success: true as const, applicationId: application.id };
    });

    if (!result.success) return result;
    revalidatePath("/admin/applications");
    return result;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to create re-assessment application";
    console.error("[createReassessmentApplicationAction] error:", err);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// addSecondParentAction (dual-parent — secondary contributor invite)
// ---------------------------------------------------------------------------

/**
 * Invites a SECOND parent to contribute to an existing application
 * (dual-parent / separated-parent case, backlog #20, PR 3).
 *
 * Mirrors `createInvitationAction`'s hardening exactly:
 *
 *   1. Validate input (Zod). ADMIN or ASSESSOR may invite (the plan allows
 *      assessors to add a second parent, unlike the ADMIN-only applicant
 *      invite).
 *   2. Guard the application exists and does NOT already have a SECONDARY
 *      contributor (the DB UNIQUE(application_id, role) also enforces this).
 *   3. De-dupe by email: if a Profile with that email already exists we LINK
 *      it (reuse its id as the contributor profileId) and do NOT create a new
 *      Supabase auth user. Otherwise we create the auth user up front with
 *      `email_confirm: true` (suppresses the built-in OTP) and roll it back on
 *      any failure.
 *   4. In one withAdminContext tx: ensure the Profile exists, create the
 *      SECONDARY ApplicationContributor (status INVITED), create a scoped
 *      Invitation (application_id set → secondary-parent invite), and write an
 *      audit log.
 *   5. Send the SECONDARY_PARENT_INVITE email inside the rollback boundary. On
 *      email failure, delete the invitation + contributor, delete the auth
 *      user (only if we created it), and write a failure audit entry.
 *
 * The contributor's profileId may equal an existing applicant/staff profile;
 * we never create a new auth user for an existing profile, so we never strand
 * an orphan auth row.
 */

const SecondParentSchema = z.object({
  applicationId: z.string().uuid("A valid application is required"),
  email: z.string().email("A valid email address is required"),
  firstName: z.string().max(100).optional(),
  lastName: z.string().max(100).optional(),
});

export async function addSecondParentAction(
  applicationId: string,
  email: string,
  firstName?: string,
  lastName?: string
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN, Role.ASSESSOR]);

  const parsed = SecondParentSchema.safeParse({
    applicationId,
    email,
    firstName: firstName || undefined,
    lastName: lastName || undefined,
  });
  if (!parsed.success) {
    return {
      success: false,
      fieldErrors: parsed.error.flatten().fieldErrors as Record<
        string,
        string[]
      >,
    };
  }

  const {
    applicationId: appId,
    email: cleanEmail,
    firstName: cleanFirst,
    lastName: cleanLast,
  } = parsed.data;

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();

  // 1. Load the application + guard against an existing SECONDARY contributor,
  //    and resolve any existing profile for de-dupe-by-email. All reads happen
  //    before we provision an auth user so we never leave an orphan behind.
  let application: {
    id: string;
    roundId: string;
    school: School;
    childName: string;
    academicYear: string;
  };
  let existingProfileId: string | null = null;
  try {
    const loaded = await withAdminContext(async (tx) => {
      const app = await tx.application.findUnique({
        where: { id: appId },
        select: {
          id: true,
          roundId: true,
          school: true,
          childName: true,
          round: { select: { academicYear: true } },
          contributors: {
            where: { role: ApplicationContributorRole.SECONDARY },
            select: { id: true },
          },
        },
      });

      if (!app) {
        return { ok: false as const, error: "Application not found." };
      }
      if (app.contributors.length > 0) {
        return {
          ok: false as const,
          error: "A second parent has already been added to this application.",
        };
      }

      const profile = await tx.profile.findUnique({
        where: { email: cleanEmail },
        select: { id: true },
      });

      return {
        ok: true as const,
        application: {
          id: app.id,
          roundId: app.roundId,
          school: app.school,
          childName: app.childName,
          academicYear: app.round.academicYear,
        },
        existingProfileId: profile?.id ?? null,
      };
    });

    if (!loaded.ok) {
      return { success: false, error: loaded.error };
    }
    application = loaded.application;
    existingProfileId = loaded.existingProfileId;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to load application";
    console.error("[invitations] addSecondParentAction load error:", err);
    return { success: false, error: message };
  }

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  const secondaryName = composeApplicantName(cleanFirst, cleanLast);

  // 2. De-dupe by email. If a profile already exists, LINK it — never create a
  //    second auth user. Otherwise provision one up front (rolled back on any
  //    failure below).
  let profileId: string;
  let createdAuthUser = false;
  if (existingProfileId) {
    profileId = existingProfileId;
  } else {
    const tempPassword = randomBytes(24).toString("base64url");
    const { data: created, error: supabaseError } =
      await supabase.auth.admin.createUser({
        email: cleanEmail,
        password: tempPassword,
        email_confirm: true,
        app_metadata: { role: "APPLICANT" },
      });

    if (supabaseError || !created?.user) {
      const message = supabaseError?.message ?? "Failed to create auth user";
      console.error(
        "[invitations] addSecondParentAction createUser error:",
        supabaseError
      );
      return { success: false, error: message };
    }
    profileId = created.user.id;
    createdAuthUser = true;
  }

  // Helper: roll back a freshly-created auth user (no-op when we linked an
  // existing profile).
  const rollbackAuthUser = async () => {
    if (!createdAuthUser) return;
    await supabase.auth.admin.deleteUser(profileId).catch((err) => {
      console.error(
        "[invitations] addSecondParentAction auth rollback failed:",
        err
      );
    });
  };

  // 3. Profile + SECONDARY contributor + scoped Invitation + audit, one tx.
  let invitationId: string;
  let invitationToken: string;
  try {
    const result = await withAdminContext(async (tx) => {
      const profile = await createProfile(tx, {
        id: profileId,
        email: cleanEmail,
        role: Role.APPLICANT,
        firstName: cleanFirst,
        lastName: cleanLast,
      });
      if (!profile.success) {
        return { success: false as const, error: profile.error };
      }

      const contributor = await tx.applicationContributor.create({
        data: {
          applicationId: application.id,
          profileId,
          role: ApplicationContributorRole.SECONDARY,
          status: ApplicationContributorStatus.INVITED,
          invitedById: user.id,
          invitedAt: new Date(),
        },
      });

      const inv = await createInvitation(tx, {
        email: cleanEmail,
        firstName: cleanFirst,
        lastName: cleanLast,
        childName: application.childName,
        school: application.school,
        roundId: application.roundId,
        applicationId: application.id,
        authUserId: profileId,
        createdBy: user.id,
        expiresAt,
      });

      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.ADD_SECOND_PARENT,
        entityType: AUDIT_ENTITY_TYPES.ApplicationContributor,
        entityId: contributor.id,
        context: `Invited second parent ${cleanEmail} to application ${application.id}`,
        metadata: {
          email: cleanEmail,
          applicationId: application.id,
          profileId,
          linkedExistingProfile: !createdAuthUser,
          authUserId: profileId,
        },
      });

      return {
        success: true as const,
        contributorId: contributor.id,
        invitationId: inv.id,
        token: inv.token,
      };
    });

    if (!result.success) {
      await rollbackAuthUser();
      return {
        success: false,
        error: result.error ?? "Failed to add second parent",
      };
    }

    invitationId = result.invitationId;
    invitationToken = result.token;
  } catch (err) {
    await rollbackAuthUser();
    const message =
      err instanceof Error ? err.message : "Failed to add second parent";
    console.error("[invitations] addSecondParentAction error:", err);
    return { success: false, error: message };
  }

  // 4. Send the SECONDARY_PARENT_INVITE email inside the rollback boundary.
  const emailResult = await sendEmail(cleanEmail, "SECONDARY_PARENT_INVITE", {
    secondary_parent_name: secondaryName || cleanEmail,
    child_name: application.childName,
    school: schoolLabel(application.school),
    round_year: application.academicYear,
    registration_link: `${appUrl}/register?token=${invitationToken}`,
    deadline: expiresAt.toLocaleDateString("en-GB"),
  });

  if (!emailResult.success) {
    console.error(
      "[invitations] addSecondParentAction email error:",
      emailResult.error
    );

    // Roll back the invitation + contributor and record the failure. The
    // contributor is deleted by the invitation? No — they are independent
    // rows, so delete both explicitly.
    await withAdminContext(async (tx) => {
      await tx.invitation
        .delete({ where: { id: invitationId } })
        .catch((err) => {
          console.error(
            "[invitations] addSecondParentAction invitation rollback failed:",
            err
          );
        });
      await tx.applicationContributor
        .deleteMany({
          where: {
            applicationId: application.id,
            role: ApplicationContributorRole.SECONDARY,
          },
        })
        .catch((err) => {
          console.error(
            "[invitations] addSecondParentAction contributor rollback failed:",
            err
          );
        });
      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.ADD_SECOND_PARENT_FAILED,
        entityType: AUDIT_ENTITY_TYPES.ApplicationContributor,
        entityId: application.id,
        context: `Second-parent invite to ${cleanEmail} rolled back — email failed to send`,
        metadata: {
          email: cleanEmail,
          applicationId: application.id,
          profileId,
          emailError: emailResult.error ?? null,
        },
      });
    }).catch((err) => {
      console.error(
        "[invitations] addSecondParentAction rollback tx failed:",
        err
      );
    });

    await rollbackAuthUser();

    revalidatePath(`/applications/${application.id}`);
    return {
      success: false,
      error: `Email failed to send. The second-parent invite was rolled back — please try again. (${emailResult.error})`,
    };
  }

  revalidatePath(`/applications/${application.id}`);
  return { success: true };
}
