"use server";

/**
 * Server actions for invitation management.
 *
 * Mirrors the hardened staff invite pattern (`inviteStaffAction` in
 * `src/app/(admin)/users/actions.ts`):
 *
 *   1. Validate input.
 *   2. Create Supabase auth user up front with a throwaway password and
 *      `email_confirm: true` so Supabase does not fire its system invite
 *      OTP email.
 *   3. Inside one `withAdminContext(tx)` transaction, upsert the Profile,
 *      create the Invitation row (token auto-generated by the helper) and
 *      write the audit log.
 *   4. On any failure between steps 3a–3c, roll back the auth user so we
 *      never leave an orphan `auth.users` row.
 *   5. Send the branded Resend INVITATION email with the
 *      `?token=<token>` link as the registration URL.
 */

import { randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import {
  ApplicationContributorRole,
  ApplicationContributorStatus,
  EntryYearGroup,
  InvitationSituation,
  InvitationStatus,
  RoundStatus,
  School,
  type ApplicationType,
} from "@prisma/client";
import { requireRole, Role } from "@/lib/auth/roles";
import {
  createInvitation,
  generateInvitationToken,
  getActiveBursaryHolders,
} from "@/lib/db/queries/invitations";
import { createSupabaseAdminClient } from "@/lib/auth/supabase-admin";
import { provisionApplicantAuthUser } from "@/lib/auth/provision-applicant";
import { createProfile } from "@/lib/auth/create-profile";
import { getAppUrl } from "@/lib/app-url";
import { sendEmail, normaliseBccAddress } from "@/lib/email/send";
import {
  invitationDeadlineFields,
  INVITATION_ROUND_DEADLINE_SELECT,
} from "@/lib/email/invitation-deadline";
import {
  deadlineTypeForSituation,
  openingDateMergeField,
  resolveInvitationTemplate,
} from "@/lib/email/invitation-template";
import type { SubmissionDeadlineRound } from "@/lib/rounds/submission-deadline";
import {
  invitationScenarioFields,
  ROUND_WINDOWS_SELECT,
} from "@/lib/rounds/window-consumption";
import { withAdminContext } from "@/lib/db/prisma";
import { createAuditLog } from "@/lib/audit/log";
import {
  prepopulateReassessment,
  getPreviousYearApplication,
  getPreviousYearReferenceSource,
} from "@/lib/db/queries/reassessment";
import { ensurePrimaryContributor } from "@/lib/db/queries/contributors";
import { applicationCreateData } from "@/lib/applications/status";
import { resolveRolloverReference } from "@/lib/applications/reference";
import { composeChildName } from "@/lib/applications/child-name";
import { listOpenRounds } from "@/lib/db/queries/reports";

import { AUDIT_ACTIONS, AUDIT_ENTITY_TYPES } from "@/lib/audit/actions";

// ---------------------------------------------------------------------------
// Validation schema
// ---------------------------------------------------------------------------

// Epic 04 (§5.2 / acceptance): the residual single-send ("quick invite") form
// now REQUIRES surname, child name and school — the same minimum the contact
// register enforces — so partial invite data can no longer slip through. The
// from-contact flow is the recommended path; this is the exception.
const InvitationSchema = z.object({
  email: z.string().email("A valid email address is required"),
  firstName: z.string().optional(),
  lastName: z.string().trim().min(1, "A surname is required"),
  // Epic 15 G2 (CH-09): the child's identity is captured SPLIT (first name +
  // surname) plus date of birth — the single `childName` string is composed
  // server-side for the legacy backing store.
  childFirstName: z
    .string()
    .trim()
    .min(1, "The child's first name is required"),
  childLastName: z.string().trim().min(1, "The child's surname is required"),
  childDob: z
    .string()
    .trim()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Enter the child's date of birth"),
  school: z.nativeEnum(School, { error: "A school is required" }),
  // Q1 (Brian, 2026-08-14): the entry year-group is JWF-facing only — the
  // applicant can never enter one — so the quick-invite must capture it here or
  // the application created on acceptance would have no year-group at all.
  entryYearGroup: z.nativeEnum(EntryYearGroup, {
    error: () => ({ message: "An entry school year is required" }),
  }),
  roundId: z.string().uuid("An application round is required"),
  // Epic 14 B3 (CG-26, LA-3) — the 3-way situation choice; the school half of
  // the template resolves from `school`. Defaults to NEW so the quick-invite
  // keeps working for callers that don't send it.
  situation: z.nativeEnum(InvitationSituation).default(InvitationSituation.NEW),
});

// ---------------------------------------------------------------------------
// Result type
// ---------------------------------------------------------------------------

export interface InvitationActionResult {
  success: boolean;
  error?: string;
  fieldErrors?: Record<string, string[]>;
  /** Epic 15 X2 (CI-04): set on a no-send create — the admin copies this
   *  link and sends it from their own mailbox. */
  registrationLink?: string;
}

export interface BatchInviteResult {
  sent: number;
  failed: number;
  errors: string[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Composes a single-line applicant display name from the structured first /
 * last fields, falling back to the empty string.
 */
function composeApplicantName(
  firstName: string | undefined,
  lastName: string | undefined
): string {
  return [firstName, lastName].filter(Boolean).join(" ").trim();
}

function schoolLabel(school: School | undefined | null): string {
  if (!school) return "";
  return school === "TRINITY" ? "Trinity School" : "Whitgift School";
}

// ---------------------------------------------------------------------------
// createInvitationAction (hardened — mirrors inviteStaffAction)
// ---------------------------------------------------------------------------

export async function createInvitationAction(
  formData: FormData
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  const raw = {
    email: formData.get("email") as string,
    firstName: (formData.get("firstName") as string) || undefined,
    lastName: (formData.get("lastName") as string) || undefined,
    childFirstName: (formData.get("childFirstName") as string) || undefined,
    childLastName: (formData.get("childLastName") as string) || undefined,
    childDob: (formData.get("childDob") as string) || undefined,
    school: (formData.get("school") as string) || undefined,
    entryYearGroup: (formData.get("entryYearGroup") as string) || undefined,
    roundId: (formData.get("roundId") as string) || undefined,
    situation: (formData.get("situation") as string) || undefined,
  };
  // Epic 15 X2 (CI-04): "Don't email — I'll send the link myself".
  const skipEmail = formData.get("skipEmail") === "1";
  // CH-32 — optional blind copy on the individual invite. Blank means no copy;
  // an invalid address is rejected before anything is created, because an
  // invitation is not worth rolling back over a typo in a BCC box.
  const bccResult = normaliseBccAddress(formData.get("bcc") as string | null);
  if (!bccResult.ok) {
    return {
      success: false,
      fieldErrors: { bcc: ["That BCC address is not a valid email."] },
    };
  }
  // A no-send create has no email to copy (the second half of CH-32's default:
  // "no copy when using Don't email — I'll send the link myself").
  const bcc = skipEmail ? undefined : bccResult.bcc;

  const parsed = InvitationSchema.safeParse(raw);
  if (!parsed.success) {
    return {
      success: false,
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const {
    email,
    firstName,
    lastName,
    childFirstName,
    childLastName,
    school,
    entryYearGroup,
    roundId,
    situation,
  } = parsed.data;

  // The composed backing store (legacy consumers read `childName`).
  const childName = composeChildName(childFirstName, childLastName);
  const childDob = new Date(`${parsed.data.childDob}T00:00:00.000Z`);

  const effectiveApplicantName = composeApplicantName(firstName, lastName);

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();

  // 1. Provision the auth user. Epic 14 E1 (CG-04): an email that already
  //    belongs to a registered parent is REUSED (a second child on one
  //    login), not an error; only genuinely new emails create an auth user.
  //    email_confirm: true suppresses the built-in OTP email — only the
  //    branded Resend message reaches the applicant.
  const provisioned = await provisionApplicantAuthUser(supabase, email);
  if (!provisioned.ok) {
    console.error(
      "[invitations] createInvitationAction provisioning error:",
      provisioned.error
    );
    return { success: false, error: provisioned.error };
  }
  const authUserId = provisioned.authUserId;
  const createdAuthUser = provisioned.created;

  // 2. Profile + Invitation + audit log under one admin context. Any throw
  //    rolls back the auth user.
  let invitationId: string;
  let invitationToken: string;
  let academicYear = "";
  // Deadline columns for the {{deadline}} merge field (E1) — read inside the
  // same tx that resolves the academic year, so no extra round query.
  let deadlineRound: SubmissionDeadlineRound | null = null;
  // B3 — the round's portal opening date feeds the rolling template's
  // {{opening_date}}; null when the invitation carries no round.
  let roundOpenDate: Date | null = null;
  try {
    const result = await withAdminContext(async (tx) => {
      const profile = await createProfile(tx, {
        id: authUserId,
        email,
        role: Role.APPLICANT,
        firstName,
        lastName,
      });
      if (!profile.success) {
        return { success: false as const, error: profile.error };
      }

      const inv = await createInvitation(tx, {
        email,
        firstName,
        lastName,
        childName,
        childFirstName,
        childLastName,
        childDob,
        school,
        entryYearGroup,
        roundId,
        situation,
        authUserId,
        createdBy: user.id,
        expiresAt,
      });

      let year = "";
      let roundDeadline: SubmissionDeadlineRound | null = null;
      let openDate: Date | null = null;
      if (roundId) {
        const round = await tx.round.findUnique({
          where: { id: roundId },
          select: {
            academicYear: true,
            openDate: true,
            ...INVITATION_ROUND_DEADLINE_SELECT,
            ...ROUND_WINDOWS_SELECT,
          },
        });
        year = round?.academicYear ?? "";
        // D2 (CG-01): the stored scenario window fills null round defaults
        // and supplies the opening date (window > openDate > derived default).
        const scenario = invitationScenarioFields({
          situation,
          academicYear: round?.academicYear,
          onDate: new Date(),
          deadlineRound: round
            ? {
                closeDate: round.closeDate,
                defaultSubmissionDeadlineNew:
                  round.defaultSubmissionDeadlineNew,
                defaultSubmissionDeadlineRolling:
                  round.defaultSubmissionDeadlineRolling,
              }
            : null,
          roundOpenDate: round?.openDate ?? null,
          windows: round?.windows ?? [],
        });
        openDate = scenario.openingDate;
        roundDeadline = scenario.deadlineRound;
      }

      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.CREATE_INVITATION,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: inv.id,
        context: `Sent invitation to ${email}`,
        metadata: {
          email,
          roundId: roundId ?? null,
          authUserId,
        },
      });

      return {
        success: true as const,
        invitationId: inv.id,
        token: inv.token,
        academicYear: year,
        roundDeadline,
        roundOpenDate: openDate,
      };
    });

    if (!result.success) {
      // E1: only a FRESHLY created auth user is rolled back — deleting a
      // reused one would destroy the parent's real login.
      if (createdAuthUser) {
        await supabase.auth.admin.deleteUser(authUserId).catch((err) => {
          console.error(
            "[invitations] createInvitationAction auth rollback failed:",
            err
          );
        });
      }
      return {
        success: false,
        error: result.error ?? "Failed to create invitation",
      };
    }

    invitationId = result.invitationId;
    invitationToken = result.token;
    academicYear = result.academicYear;
    deadlineRound = result.roundDeadline;
    roundOpenDate = result.roundOpenDate;
  } catch (err) {
    if (createdAuthUser) {
      await supabase.auth.admin.deleteUser(authUserId).catch((rollbackErr) => {
        console.error(
          "[invitations] createInvitationAction auth rollback failed:",
          rollbackErr
        );
      });
    }
    const message =
      err instanceof Error ? err.message : "Failed to send invitation";
    console.error("[invitations] createInvitationAction error:", err);
    return { success: false, error: message };
  }

  // Epic 15 X2 (CI-04): a no-send create stops here — the invitation exists
  // (30-day token, resend available later); the admin sends the link.
  if (skipEmail) {
    revalidatePath("/invitations");
    return {
      success: true,
      registrationLink: `${appUrl}/register?token=${invitationToken}`,
    };
  }

  // 3. Send branded INVITATION email. The email is now inside the rollback
  //    boundary (#5): a send failure would otherwise leave a PENDING orphan
  //    row + auth user that looks valid but whose token never reached the
  //    recipient. On failure we hard-roll-back — delete the invitation row,
  //    delete the auth user, and write a failure audit entry so the attempt
  //    stays visible — then surface a clear error to the admin.
  // B3 (CG-26): the template variant follows the chosen situation and the
  // school; the {{deadline}} default follows the situation too (rolling-over
  // invites get the round's rolling date).
  const emailResult = await sendEmail(
    email,
    resolveInvitationTemplate(situation, school),
    {
      applicant_name: effectiveApplicantName || email,
      child_name: childName ?? "",
      school: schoolLabel(school),
      round_year: academicYear,
      registration_link: `${appUrl}/register?token=${invitationToken}`,
      opening_date: openingDateMergeField(
        roundOpenDate ? { openDate: roundOpenDate } : null
      ),
      // E1/CF-11: {{deadline}} is the SUBMISSION deadline for the round this
      // invitation is for; {{link_expiry}} carries the token expiry that used
      // to masquerade as it.
      ...invitationDeadlineFields(
        deadlineRound,
        deadlineTypeForSituation(situation),
        expiresAt
      ),
    },
    // CH-32 — blind-copy the bursary inbox so the send is on record.
    bcc ? { bcc } : undefined
  );

  if (!emailResult.success) {
    console.error(
      "[invitations] createInvitationAction email error:",
      emailResult.error
    );

    // Roll back the just-created invitation row and record the failure.
    await withAdminContext(async (tx) => {
      await tx.invitation.delete({ where: { id: invitationId } }).catch((err) => {
        console.error(
          "[invitations] createInvitationAction invitation rollback failed:",
          err
        );
      });
      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.CREATE_INVITATION_FAILED,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: invitationId,
        context: `Invitation to ${email} rolled back — email failed to send`,
        metadata: {
          email,
          roundId: roundId ?? null,
          authUserId,
          emailError: emailResult.error ?? null,
        },
      });
    }).catch((err) => {
      console.error(
        "[invitations] createInvitationAction rollback tx failed:",
        err
      );
    });

    // Roll back the auth user so we never leave an orphan account behind —
    // but only one WE created this call (E1: a reused login must survive).
    if (createdAuthUser) {
      await supabase.auth.admin.deleteUser(authUserId).catch((err) => {
        console.error(
          "[invitations] createInvitationAction auth rollback failed:",
          err
        );
      });
    }

    revalidatePath("/invitations");
    return {
      success: false,
      error: `Email failed to send. The invitation was rolled back — please try again. (${emailResult.error})`,
    };
  }

  void invitationId; // referenced for type completeness; used by audit log above

  revalidatePath("/invitations");
  return { success: true };
}

// ---------------------------------------------------------------------------
// Reassessment invite — shared hardened core
// ---------------------------------------------------------------------------

type EligibleHolder = Awaited<
  ReturnType<typeof getActiveBursaryHolders>
>[number];

/**
 * Provisions one re-assessment invitation for a single eligible bursary holder
 * with the same auth-user-up-front + rollback hardening as
 * `createInvitationAction`. Mutates `result` in place (increments `sent` /
 * `failed`, appends to `errors`). Shared by both the all-holders batch action
 * and the selective action so the auth-user / rollback logic lives in exactly
 * one place.
 */
async function sendReassessmentInviteForHolder(
  holder: EligibleHolder,
  ctx: {
    roundId: string;
    academicYear: string;
    /**
     * The target round's deadline columns, resolved once by the batch caller —
     * every holder in a batch shares one round, so this is not re-read per row.
     * Null only if the round could not be read.
     */
    deadlineRound: SubmissionDeadlineRound | null;
    userId: string;
    supabase: ReturnType<typeof createSupabaseAdminClient>;
    appUrl: string;
  },
  result: BatchInviteResult
): Promise<void> {
  const { roundId, academicYear, userId, supabase, appUrl } = ctx;
  const { email, firstName, lastName } = holder.leadApplicant;
  const applicantName =
    composeApplicantName(firstName ?? undefined, lastName ?? undefined) ||
    email;

  // Per-row auth-user provisioning.
  let authUserId: string | null = null;
  try {
    const tempPassword = randomBytes(24).toString("base64url");
    const { data: created, error: supabaseError } =
      await supabase.auth.admin.createUser({
        email,
        password: tempPassword,
        email_confirm: true,
        app_metadata: { role: "APPLICANT" },
      });

    if (supabaseError || !created?.user) {
      throw new Error(supabaseError?.message ?? "Failed to create auth user");
    }
    authUserId = created.user.id;

    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + 30);

    const txResult = await withAdminContext(async (tx) => {
      const profile = await createProfile(tx, {
        id: authUserId!,
        email,
        role: Role.APPLICANT,
        firstName: firstName ?? undefined,
        lastName: lastName ?? undefined,
      });
      if (!profile.success) {
        return { success: false as const, error: profile.error };
      }

      const invitation = await createInvitation(tx, {
        email,
        firstName: firstName ?? undefined,
        lastName: lastName ?? undefined,
        childName: holder.childName,
        school: holder.school,
        roundId,
        bursaryAccountId: holder.id,
        authUserId: authUserId!,
        createdBy: userId,
        expiresAt,
      });

      await createAuditLog(tx, {
        userId,
        action: AUDIT_ACTIONS.BATCH_REASSESSMENT_INVITE,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: invitation.id,
        context: `Sent reassessment invitation to ${email}`,
        metadata: {
          email,
          roundId,
          bursaryAccountId: holder.id,
          authUserId,
        },
      });

      return {
        success: true as const,
        invitationId: invitation.id,
        token: invitation.token,
        expiresAt,
      };
    });

    if (!txResult.success) {
      throw new Error(txResult.error ?? "Failed to create invitation");
    }

    // Send branded reassessment email
    const emailResult = await sendEmail(email, "REASSESSMENT", {
      applicant_name: applicantName,
      child_name: holder.childName,
      school: schoolLabel(holder.school),
      round_year: academicYear,
      registration_link: `${appUrl}/register?token=${txResult.token}`,
      // E1/CF-12: a re-assessment invitation is by definition ROLLING_OVER, so
      // {{deadline}} resolves against the round's rolling submission date (the
      // April one), NOT the 30-day token expiry it used to carry.
      ...invitationDeadlineFields(
        ctx.deadlineRound,
        "ROLLING_OVER",
        txResult.expiresAt
      ),
    });

    if (emailResult.success) {
      result.sent++;
    } else {
      result.failed++;
      result.errors.push(`${email}: ${emailResult.error}`);
    }
  } catch (err) {
    // Roll back the auth user if we got that far.
    if (authUserId) {
      await supabase.auth.admin.deleteUser(authUserId).catch((rollbackErr) => {
        console.error(
          `[reassessment-invite] auth rollback failed for ${email}:`,
          rollbackErr
        );
      });
    }
    const message = err instanceof Error ? err.message : "Unknown error";
    result.failed++;
    result.errors.push(`${email}: ${message}`);
    console.error(`[reassessment-invite] Error for ${email}:`, err);
  }
}

/**
 * Loads the eligible (active, not-yet-invited) holders for a round plus the
 * round's academic year, then runs `sendReassessmentInviteForHolder` over the
 * provided holder list (already filtered/scoped by the caller). Centralises
 * the load, rate-limit delay and revalidation so both public actions share it.
 */
async function runReassessmentInvites(
  roundId: string,
  selectIds: string[] | null
): Promise<BatchInviteResult> {
  const user = await requireRole([Role.ADMIN]);

  const result: BatchInviteResult = { sent: 0, failed: 0, errors: [] };

  let eligible: EligibleHolder[] = [];
  let academicYear = "";
  // Read once for the whole batch — every holder is invited into the SAME
  // round, so the rolling-over submission deadline is identical for all of
  // them (E1; Q4: one global rolling date per round).
  let deadlineRound: SubmissionDeadlineRound | null = null;
  try {
    const loaded = await withAdminContext(async (tx) => {
      const h = await getActiveBursaryHolders(tx, roundId);
      const round = await tx.round.findUnique({
        where: { id: roundId },
        select: {
          academicYear: true,
          ...INVITATION_ROUND_DEADLINE_SELECT,
          ...ROUND_WINDOWS_SELECT,
        },
      });
      return {
        holders: h,
        academicYear: round?.academicYear ?? "",
        roundWindows: round?.windows ?? [],
        deadlineRound: round
          ? {
              closeDate: round.closeDate,
              defaultSubmissionDeadlineNew: round.defaultSubmissionDeadlineNew,
              defaultSubmissionDeadlineRolling:
                round.defaultSubmissionDeadlineRolling,
            }
          : null,
      };
    });
    eligible = loaded.holders;
    academicYear = loaded.academicYear;
    // D2 (CG-01): a stored RA window's submit-by fills the rolling default
    // when the round column is null — resolved ONCE for the whole batch
    // (every holder is invited into the same round on the same clock).
    deadlineRound = invitationScenarioFields({
      situation: InvitationSituation.ROLLING_OVER,
      academicYear,
      onDate: new Date(),
      deadlineRound: loaded.deadlineRound,
      roundOpenDate: null,
      windows: loaded.roundWindows,
    }).deadlineRound;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to load bursary holders";
    console.error("[reassessment-invite] Load error:", err);
    result.errors.push(message);
    return result;
  }

  // When a selection is supplied, filter to it — defensively ignoring any id
  // that is not currently eligible (already invited / inactive). When null,
  // invite all eligible holders (the legacy batch behaviour).
  const holders =
    selectIds === null
      ? eligible
      : eligible.filter((h) => selectIds.includes(h.id));

  if (holders.length === 0) {
    result.errors.push("No eligible holders selected");
    return result;
  }

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();
  const ctx = {
    roundId,
    academicYear,
    deadlineRound,
    userId: user.id,
    supabase,
    appUrl,
  };

  for (let i = 0; i < holders.length; i++) {
    await sendReassessmentInviteForHolder(holders[i], ctx, result);

    // Rate-limit delay between sends (100 ms), skip after last item
    if (i < holders.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }

  revalidatePath("/invitations");
  return result;
}

// ---------------------------------------------------------------------------
// batchReassessmentInviteAction (hardened — per-row auth-user rollback)
// ---------------------------------------------------------------------------

/**
 * Sends reassessment invitations to ALL active bursary holders that have not
 * yet been invited for the specified round. Thin wrapper over the shared
 * `runReassessmentInvites` core (selectIds = null → all eligible). Retained for
 * backwards compatibility; the selective action is preferred from the UI.
 */
export async function batchReassessmentInviteAction(
  roundId: string
): Promise<BatchInviteResult> {
  return runReassessmentInvites(roundId, null);
}

// ---------------------------------------------------------------------------
// reassessmentInviteSelectedAction (selective — staff pick the holders)
// ---------------------------------------------------------------------------

/**
 * Sends reassessment invitations to a STAFF-SELECTED subset of the active
 * bursary holders for a round. Each requested id is filtered against the
 * currently-eligible set, so an id that is not eligible (already invited /
 * inactive) is silently ignored — we never invite a holder that isn't a valid
 * re-assessment candidate. Shares the exact same hardened per-row provisioning
 * + rollback as the batch action.
 */
export async function reassessmentInviteSelectedAction(
  roundId: string,
  bursaryAccountIds: string[]
): Promise<BatchInviteResult> {
  const ids = Array.isArray(bursaryAccountIds) ? bursaryAccountIds : [];
  if (ids.length === 0) {
    return { sent: 0, failed: 0, errors: ["No eligible holders selected"] };
  }
  return runReassessmentInvites(roundId, ids);
}

// ---------------------------------------------------------------------------
// bulkReassessmentInviteFromApplicationsAction (queue bulk action)
// ---------------------------------------------------------------------------

export interface BulkReassessmentFromApplicationsResult {
  sent: number;
  failed: number;
  skipped: number;
  errors: string[];
  targetRound: string | null;
}

/**
 * Queue-driven re-assessment invite. The admin selects rows in the application
 * queue (prior-round winning applications linked to a BursaryAccount) and fires
 * this action. It:
 *
 *   1. Resolves the OPEN round to invite into. If there is none, every selected
 *      application is `skipped` and we return early.
 *   2. Loads the selected applications' `bursaryAccountId`s, keeping the
 *      non-null, de-duplicated set (the candidate accounts).
 *   3. Delegates to `runReassessmentInvites(openRound.id, accountIds)`, which
 *      itself re-filters those ids against the genuinely-eligible holders for
 *      that round (active + not-yet-invited) before sending.
 *
 * `skipped` semantics: a selected application is "skipped" when it did not
 * result in an invite for a reason OTHER than a send failure — i.e. it had no
 * bursary account, OR its account was not eligible for the open round (already
 * invited / inactive), OR two selected applications share one account (the
 * account is invited once, the duplicate is skipped). We compute it precisely
 * as:
 *
 *   skipped = selectedCount − sent − failed
 *
 * which is exact here because every distinct candidate account that
 * `runReassessmentInvites` actually attempts increments exactly one of `sent`
 * or `failed`, and every other selected application (no account / ineligible /
 * duplicate account) contributes neither — so it falls into `skipped`.
 */
export async function bulkReassessmentInviteFromApplicationsAction(
  applicationIds: string[],
  targetRoundId?: string | null
): Promise<BulkReassessmentFromApplicationsResult> {
  await requireRole([Role.ADMIN]);

  const ids = Array.isArray(applicationIds) ? applicationIds : [];

  // Cap input to bound the work + protect the per-row email rate limiting.
  if (ids.length === 0) {
    return {
      sent: 0,
      failed: 0,
      skipped: 0,
      errors: ["No applications selected"],
      targetRound: null,
    };
  }
  if (ids.length > 500) {
    return {
      sent: 0,
      failed: 0,
      skipped: ids.length,
      errors: ["Too many applications selected (max 500)"],
      targetRound: null,
    };
  }

  // 1. Resolve the OPEN round to invite into.
  //
  //    Epic 03 (concurrent rounds): multiple rounds can be OPEN at once, so we
  //    must NEVER silently fan invites into "the" open round. Resolution rules:
  //      - An explicit `targetRoundId` (the round the queue is scoped to) is
  //        authoritative — we validate it exists and is OPEN.
  //      - Without one, we fall back ONLY when exactly one round is OPEN (the
  //        unambiguous case). If two or more are OPEN and no round was chosen,
  //        we refuse rather than guess.
  let openRound: { id: string; academicYear: string } | null = null;
  try {
    const resolved = await withAdminContext(async (tx) => {
      if (targetRoundId) {
        const r = await tx.round.findUnique({
          where: { id: targetRoundId },
          select: { id: true, academicYear: true, status: true },
        });
        return { kind: "explicit" as const, round: r, openCount: 0 };
      }
      const open = await listOpenRounds(tx);
      return {
        kind: "fallback" as const,
        round: open[0] ?? null,
        openCount: open.length,
      };
    });

    if (resolved.kind === "explicit") {
      if (!resolved.round) {
        return {
          sent: 0,
          failed: 0,
          skipped: ids.length,
          errors: ["Selected round not found"],
          targetRound: null,
        };
      }
      if (resolved.round.status !== RoundStatus.OPEN) {
        return {
          sent: 0,
          failed: 0,
          skipped: ids.length,
          errors: [
            `Round ${resolved.round.academicYear} is ${resolved.round.status}; re-assessment invites can only target an OPEN round`,
          ],
          targetRound: null,
        };
      }
      openRound = {
        id: resolved.round.id,
        academicYear: resolved.round.academicYear,
      };
    } else {
      if (resolved.openCount > 1) {
        return {
          sent: 0,
          failed: 0,
          skipped: ids.length,
          errors: [
            "More than one round is open — scope the queue to a specific round before sending re-assessment invites",
          ],
          targetRound: null,
        };
      }
      if (resolved.round) {
        openRound = {
          id: resolved.round.id,
          academicYear: resolved.round.academicYear,
        };
      }
    }
  } catch (err) {
    console.error(
      "[invitations] bulkReassessmentInviteFromApplicationsAction round load error:",
      err
    );
    return {
      sent: 0,
      failed: 0,
      skipped: ids.length,
      errors: ["Failed to resolve the open round"],
      targetRound: null,
    };
  }

  if (!openRound) {
    return {
      sent: 0,
      failed: 0,
      skipped: ids.length,
      errors: ["No open round to invite into"],
      targetRound: null,
    };
  }

  // 2. Load the selected applications' bursary-account ids (non-null, deduped).
  let accountIds: string[] = [];
  try {
    const rows = await withAdminContext((tx) =>
      tx.application.findMany({
        where: { id: { in: ids } },
        select: { bursaryAccountId: true },
      })
    );
    accountIds = Array.from(
      new Set(
        rows
          .map((r) => r.bursaryAccountId)
          .filter((id): id is string => id !== null)
      )
    );
  } catch (err) {
    console.error(
      "[invitations] bulkReassessmentInviteFromApplicationsAction load error:",
      err
    );
    return {
      sent: 0,
      failed: 0,
      skipped: ids.length,
      errors: ["Failed to load selected applications"],
      targetRound: openRound.academicYear,
    };
  }

  if (accountIds.length === 0) {
    return {
      sent: 0,
      failed: 0,
      skipped: ids.length,
      errors: ["None of the selected applications are linked to a bursary holder"],
      targetRound: openRound.academicYear,
    };
  }

  // 3. Delegate to the shared core, which re-filters accountIds to the holders
  //    actually eligible for the open round and provisions each invite.
  const batch = await runReassessmentInvites(openRound.id, accountIds);

  // `runReassessmentInvites` pushes a "No eligible holders selected" error when
  // nothing in the set was eligible — that's a skip, not a user-facing failure,
  // so drop it from the surfaced errors when there were no real send failures.
  const errors =
    batch.sent === 0 && batch.failed === 0
      ? batch.errors.filter((e) => e !== "No eligible holders selected")
      : batch.errors;

  const skipped = Math.max(0, ids.length - batch.sent - batch.failed);

  return {
    sent: batch.sent,
    failed: batch.failed,
    skipped,
    errors,
    targetRound: openRound.academicYear,
  };
}

// ---------------------------------------------------------------------------
// resendInvitationAction
// ---------------------------------------------------------------------------

/**
 * Regenerates the single-use token, resets the 30-day expiry, and re-sends
 * the branded INVITATION email. Only valid on PENDING rows.
 */
export async function resendInvitationAction(
  invitationId: string
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  if (!invitationId || typeof invitationId !== "string") {
    return { success: false, error: "Invalid invitation id." };
  }

  try {
    const invitation = await withAdminContext((tx) =>
      tx.invitation.findUnique({
        where: { id: invitationId },
        include: {
          round: {
            select: {
              academicYear: true,
              openDate: true,
              ...INVITATION_ROUND_DEADLINE_SELECT,
              ...ROUND_WINDOWS_SELECT,
            },
          },
          // A resend must reproduce the ORIGINAL invitation's submission
          // deadline, so it needs the linked application's own type + override
          // when there is one (second-parent invites) — E1.
          application: {
            select: { applicationType: true, submissionDeadlineAt: true },
          },
        },
      })
    );

    if (!invitation) {
      return { success: false, error: "Invitation not found." };
    }

    if (invitation.status !== InvitationStatus.PENDING) {
      return {
        success: false,
        error: "Only pending invitations can be resent.",
      };
    }

    const newToken = generateInvitationToken();
    const newExpiresAt = new Date();
    newExpiresAt.setDate(newExpiresAt.getDate() + 30);

    await withAdminContext(async (tx) => {
      await tx.invitation.update({
        where: { id: invitationId },
        data: {
          token: newToken,
          expiresAt: newExpiresAt,
        },
      });

      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.RESEND_INVITATION,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: invitationId,
        context: `Resent invitation to ${invitation.email}`,
        metadata: {
          email: invitation.email,
          expiresAt: newExpiresAt.toISOString(),
        },
      });
    });

    const appUrl = getAppUrl();
    const applicantName =
      composeApplicantName(
        invitation.firstName ?? undefined,
        invitation.lastName ?? undefined
      ) || invitation.email;

    // B3: a resend reuses the SAME template variant the original send chose
    // (situation persisted on the row; legacy NULL rows fall back to the
    // generic INVITATION).
    // D2 (CG-01): same window consumption as the original send.
    const scenario = invitationScenarioFields({
      situation: invitation.situation,
      academicYear: invitation.round?.academicYear,
      onDate: new Date(),
      deadlineRound: invitation.round,
      roundOpenDate: invitation.round?.openDate ?? null,
      windows: invitation.round?.windows ?? [],
    });
    const emailResult = await sendEmail(
      invitation.email,
      resolveInvitationTemplate(invitation.situation, invitation.school),
      {
      applicant_name: applicantName,
      child_name: invitation.childName ?? "",
      school: schoolLabel(invitation.school),
      round_year: invitation.round?.academicYear ?? "",
      registration_link: `${appUrl}/register?token=${newToken}`,
      opening_date: openingDateMergeField(
        scenario.openingDate ? { openDate: scenario.openingDate } : null
      ),
      // E1: a resend re-states the SAME submission deadline as the original
      // send — only {{link_expiry}} moves, because only the token was renewed.
      // Before this, every resend silently pushed the advertised "deadline"
      // another 30 days into the future.
      ...invitationDeadlineFields(
        scenario.deadlineRound,
        invitation.application?.applicationType ??
          deadlineTypeForSituation(invitation.situation),
        newExpiresAt,
        invitation.application?.submissionDeadlineAt ?? null
      ),
      }
    );

    if (!emailResult.success) {
      console.error(
        "[invitations] resendInvitationAction email error:",
        emailResult.error
      );
      return {
        success: false,
        error: `Token refreshed but email failed to send: ${emailResult.error}`,
      };
    }

    revalidatePath("/invitations");
    return { success: true };
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to resend invitation";
    console.error("[invitations] resendInvitationAction error:", err);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// revokeInvitationAction
// ---------------------------------------------------------------------------

/**
 * Marks a PENDING invitation as EXPIRED. If the invitation was never accepted
 * and we provisioned a Supabase auth user up front, soft-delete that auth
 * user so we don't leave a half-onboarded account behind.
 */
export async function revokeInvitationAction(
  invitationId: string
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  if (!invitationId || typeof invitationId !== "string") {
    return { success: false, error: "Invalid invitation id." };
  }

  try {
    const invitation = await withAdminContext((tx) =>
      tx.invitation.findUnique({ where: { id: invitationId } })
    );

    if (!invitation) {
      return { success: false, error: "Invitation not found." };
    }

    if (invitation.status !== InvitationStatus.PENDING) {
      return {
        success: false,
        error: "Only pending invitations can be revoked.",
      };
    }

    const shouldDeleteAuthUser =
      invitation.authUserId !== null && invitation.acceptedAt === null;

    await withAdminContext(async (tx) => {
      await tx.invitation.update({
        where: { id: invitationId },
        data: { status: InvitationStatus.EXPIRED },
      });

      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.REVOKE_INVITATION,
        entityType: AUDIT_ENTITY_TYPES.Invitation,
        entityId: invitationId,
        context: `Revoked invitation to ${invitation.email}`,
        metadata: {
          email: invitation.email,
          authUserId: invitation.authUserId,
          authUserDeleted: shouldDeleteAuthUser,
        },
      });
    });

    if (shouldDeleteAuthUser && invitation.authUserId) {
      const supabase = createSupabaseAdminClient();
      const { error: deleteError } = await supabase.auth.admin.deleteUser(
        invitation.authUserId
      );
      if (deleteError) {
        console.error(
          "[invitations] revokeInvitationAction auth deletion warning:",
          deleteError
        );
      }
    }

    revalidatePath("/invitations");
    return { success: true };
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to revoke invitation";
    console.error("[invitations] revokeInvitationAction error:", err);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// createReassessmentApplicationAction
// ---------------------------------------------------------------------------

const ReassessmentApplicationSchema = z.object({
  bursaryAccountId: z.string().uuid("A valid bursary account ID is required"),
  roundId: z.string().uuid("A valid round ID is required"),
});

export interface ReassessmentApplicationResult {
  success: boolean;
  applicationId?: string;
  error?: string;
}

/**
 * Creates a re-assessment application and pre-populates it with personal
 * section data from the previous year.
 *
 * Called after an applicant registers via a re-assessment invitation.
 * Links the application to the existing BursaryAccount with isReassessment: true.
 */
export async function createReassessmentApplicationAction(
  bursaryAccountId: string,
  roundId: string
): Promise<ReassessmentApplicationResult> {
  await requireRole([Role.ADMIN]);

  const parsed = ReassessmentApplicationSchema.safeParse({
    bursaryAccountId,
    roundId,
  });
  if (!parsed.success) {
    return {
      success: false,
      error: parsed.error.issues.map((i) => i.message).join("; "),
    };
  }

  try {
    const result = await withAdminContext(async (tx) => {
      // Load bursary account details
      const account = await tx.bursaryAccount.findUnique({
        where: { id: bursaryAccountId },
        include: { leadApplicant: true },
      });

      if (!account) {
        return { success: false as const, error: "Bursary account not found." };
      }

      // Reference (Epic 13, C4a/C4b). This used to be
      // `REA-${account.reference}-${roundId.slice(0,8)}` — built from the
      // bursary account's own `BA-…` code, which no longer exists.
      //
      // D13-1a / Q5: this creates a ROLLING_OVER application, so it INHERITS
      // the prior year's reference. Once that reference has been edited to the
      // external fees-system code (`TS-SMITH05-Smith, Bob`), that code is what
      // reconciliation depends on — regenerating it here would silently break
      // the link, which is exactly what Q5 was decided to prevent. It is
      // regenerated ONLY when the prior reference is still the untouched
      // default, since inheriting that verbatim would drag a stale academic
      // year onto the new year's application. A human-entered value is never
      // discarded.
      //
      // Same helper as `createReassessmentApplicationFromInvitation` — the
      // comparison lives in `resolveRolloverReference` and is deliberately NOT
      // duplicated here. `getPreviousYearReferenceSource` is its own narrow
      // read (not the heavyweight `getPreviousYearApplication` below), but both
      // share `previousYearApplicationQuery`, so they always resolve to the
      // same prior application. With no prior application it falls back to the
      // generated default.
      //
      // Unlike the invitation path, this create DOES persist `entryYearGroup`,
      // so it is passed through — the label is built from exactly the fields
      // the row will hold, which is what keeps next year's
      // recompute-and-compare consistent.
      const round = await tx.round.findUnique({
        where: { id: roundId },
        select: { academicYear: true },
      });

      const priorReferenceSource = await getPreviousYearReferenceSource(
        tx,
        bursaryAccountId,
        roundId
      );

      const reference = resolveRolloverReference(priorReferenceSource, {
        childName: account.childName,
        school: account.school,
        entryYearGroup: account.entryYearGroup,
        academicYear: round?.academicYear,
      });

      // Create the re-assessment application
      const application = await tx.application.create({
        data: {
          reference,
          roundId,
          bursaryAccountId,
          leadApplicantId: account.leadApplicantId,
          school: account.school,
          childName: account.childName,
          childDob: account.childDob,
          entryYear: account.entryYear,
          entryYearGroup: account.entryYearGroup,
          isReassessment: true,
          ...applicationCreateData("ROLLING_OVER"),
        },
      });

      // Every application must have a PRIMARY contributor from creation so the
      // section write path can tag the owner (dual-parent foundation).
      await ensurePrimaryContributor(tx, application.id, account.leadApplicantId);

      // Pre-populate from the most recent previous year application
      const previous = await getPreviousYearApplication(tx, bursaryAccountId, roundId);
      if (previous) {
        await prepopulateReassessment(tx, application.id, previous.id);
      }

      await createAuditLog(tx, {
        action: AUDIT_ACTIONS.CREATE_REASSESSMENT_APPLICATION,
        entityType: AUDIT_ENTITY_TYPES.Application,
        entityId: application.id,
        context: `Re-assessment application created for ${account.childName}`,
        metadata: {
          bursaryAccountId,
          roundId,
          previousApplicationId: previous?.id ?? null,
        },
      });

      return { success: true as const, applicationId: application.id };
    });

    if (!result.success) return result;
    revalidatePath("/admin/applications");
    return result;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to create re-assessment application";
    console.error("[createReassessmentApplicationAction] error:", err);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// addSecondParentAction (dual-parent — secondary contributor invite)
// ---------------------------------------------------------------------------

/**
 * Invites a SECOND parent to contribute to an existing application
 * (dual-parent / separated-parent case, backlog #20, PR 3).
 *
 * Mirrors `createInvitationAction`'s hardening exactly:
 *
 *   1. Validate input (Zod). ADMIN or ASSESSOR may invite (the plan allows
 *      assessors to add a second parent, unlike the ADMIN-only applicant
 *      invite).
 *   2. Guard the application exists and does NOT already have a SECONDARY
 *      contributor (the DB UNIQUE(application_id, role) also enforces this).
 *   3. De-dupe by email: if a Profile with that email already exists we LINK
 *      it (reuse its id as the contributor profileId) and do NOT create a new
 *      Supabase auth user. Otherwise we create the auth user up front with
 *      `email_confirm: true` (suppresses the built-in OTP) and roll it back on
 *      any failure.
 *   4. In one withAdminContext tx: ensure the Profile exists, create the
 *      SECONDARY ApplicationContributor (status INVITED), create a scoped
 *      Invitation (application_id set → secondary-parent invite), and write an
 *      audit log.
 *   5. Send the SECONDARY_PARENT_INVITE email inside the rollback boundary. On
 *      email failure, delete the invitation + contributor, delete the auth
 *      user (only if we created it), and write a failure audit entry.
 *
 * The contributor's profileId may equal an existing applicant/staff profile;
 * we never create a new auth user for an existing profile, so we never strand
 * an orphan auth row.
 */

const SecondParentSchema = z.object({
  applicationId: z.string().uuid("A valid application is required"),
  email: z.string().email("A valid email address is required"),
  firstName: z.string().max(100).optional(),
  lastName: z.string().max(100).optional(),
});

export async function addSecondParentAction(
  applicationId: string,
  email: string,
  firstName?: string,
  lastName?: string
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN, Role.ASSESSOR]);

  const parsed = SecondParentSchema.safeParse({
    applicationId,
    email,
    firstName: firstName || undefined,
    lastName: lastName || undefined,
  });
  if (!parsed.success) {
    return {
      success: false,
      fieldErrors: parsed.error.flatten().fieldErrors as Record<
        string,
        string[]
      >,
    };
  }

  const {
    applicationId: appId,
    email: cleanEmail,
    firstName: cleanFirst,
    lastName: cleanLast,
  } = parsed.data;

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();

  // 1. Load the application + guard against an existing SECONDARY contributor,
  //    and resolve any existing profile for de-dupe-by-email. All reads happen
  //    before we provision an auth user so we never leave an orphan behind.
  let application: {
    id: string;
    roundId: string;
    school: School;
    childName: string;
    academicYear: string;
    /** Selects which round default the invite's {{deadline}} uses (E1). */
    applicationType: ApplicationType;
    /** The application's own submit-by override, when set (E1, tier 1). */
    submissionDeadlineAt: Date | null;
    /** The round's deadline columns for tiers 2–3 (E1). */
    deadlineRound: SubmissionDeadlineRound;
  };
  let existingProfileId: string | null = null;
  try {
    const loaded = await withAdminContext(async (tx) => {
      const app = await tx.application.findUnique({
        where: { id: appId },
        select: {
          id: true,
          roundId: true,
          school: true,
          childName: true,
          applicationType: true,
          submissionDeadlineAt: true,
          round: {
            select: {
              academicYear: true,
              ...INVITATION_ROUND_DEADLINE_SELECT,
            },
          },
          contributors: {
            where: { role: ApplicationContributorRole.SECONDARY },
            select: { id: true },
          },
        },
      });

      if (!app) {
        return { ok: false as const, error: "Application not found." };
      }
      if (app.contributors.length > 0) {
        return {
          ok: false as const,
          error: "A second parent has already been added to this application.",
        };
      }

      const profile = await tx.profile.findUnique({
        where: { email: cleanEmail },
        select: { id: true },
      });

      return {
        ok: true as const,
        application: {
          id: app.id,
          roundId: app.roundId,
          school: app.school,
          childName: app.childName,
          academicYear: app.round.academicYear,
          applicationType: app.applicationType,
          submissionDeadlineAt: app.submissionDeadlineAt,
          deadlineRound: {
            closeDate: app.round.closeDate,
            defaultSubmissionDeadlineNew: app.round.defaultSubmissionDeadlineNew,
            defaultSubmissionDeadlineRolling:
              app.round.defaultSubmissionDeadlineRolling,
          },
        },
        existingProfileId: profile?.id ?? null,
      };
    });

    if (!loaded.ok) {
      return { success: false, error: loaded.error };
    }
    application = loaded.application;
    existingProfileId = loaded.existingProfileId;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to load application";
    console.error("[invitations] addSecondParentAction load error:", err);
    return { success: false, error: message };
  }

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  const secondaryName = composeApplicantName(cleanFirst, cleanLast);

  // 2. De-dupe by email. If a profile already exists, LINK it — never create a
  //    second auth user. Otherwise provision one up front (rolled back on any
  //    failure below).
  let profileId: string;
  let createdAuthUser = false;
  if (existingProfileId) {
    profileId = existingProfileId;
  } else {
    const tempPassword = randomBytes(24).toString("base64url");
    const { data: created, error: supabaseError } =
      await supabase.auth.admin.createUser({
        email: cleanEmail,
        password: tempPassword,
        email_confirm: true,
        app_metadata: { role: "APPLICANT" },
      });

    if (supabaseError || !created?.user) {
      const message = supabaseError?.message ?? "Failed to create auth user";
      console.error(
        "[invitations] addSecondParentAction createUser error:",
        supabaseError
      );
      return { success: false, error: message };
    }
    profileId = created.user.id;
    createdAuthUser = true;
  }

  // Helper: roll back a freshly-created auth user (no-op when we linked an
  // existing profile).
  const rollbackAuthUser = async () => {
    if (!createdAuthUser) return;
    await supabase.auth.admin.deleteUser(profileId).catch((err) => {
      console.error(
        "[invitations] addSecondParentAction auth rollback failed:",
        err
      );
    });
  };

  // 3. Profile + SECONDARY contributor + scoped Invitation + audit, one tx.
  let invitationId: string;
  let invitationToken: string;
  try {
    const result = await withAdminContext(async (tx) => {
      const profile = await createProfile(tx, {
        id: profileId,
        email: cleanEmail,
        role: Role.APPLICANT,
        firstName: cleanFirst,
        lastName: cleanLast,
      });
      if (!profile.success) {
        return { success: false as const, error: profile.error };
      }

      const contributor = await tx.applicationContributor.create({
        data: {
          applicationId: application.id,
          profileId,
          role: ApplicationContributorRole.SECONDARY,
          status: ApplicationContributorStatus.INVITED,
          invitedById: user.id,
          invitedAt: new Date(),
        },
      });

      const inv = await createInvitation(tx, {
        email: cleanEmail,
        firstName: cleanFirst,
        lastName: cleanLast,
        childName: application.childName,
        school: application.school,
        roundId: application.roundId,
        applicationId: application.id,
        authUserId: profileId,
        createdBy: user.id,
        expiresAt,
      });

      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.ADD_SECOND_PARENT,
        entityType: AUDIT_ENTITY_TYPES.ApplicationContributor,
        entityId: contributor.id,
        context: `Invited second parent ${cleanEmail} to application ${application.id}`,
        metadata: {
          email: cleanEmail,
          applicationId: application.id,
          profileId,
          linkedExistingProfile: !createdAuthUser,
          authUserId: profileId,
        },
      });

      return {
        success: true as const,
        contributorId: contributor.id,
        invitationId: inv.id,
        token: inv.token,
      };
    });

    if (!result.success) {
      await rollbackAuthUser();
      return {
        success: false,
        error: result.error ?? "Failed to add second parent",
      };
    }

    invitationId = result.invitationId;
    invitationToken = result.token;
  } catch (err) {
    await rollbackAuthUser();
    const message =
      err instanceof Error ? err.message : "Failed to add second parent";
    console.error("[invitations] addSecondParentAction error:", err);
    return { success: false, error: message };
  }

  // 4. Send the SECONDARY_PARENT_INVITE email inside the rollback boundary.
  const emailResult = await sendEmail(cleanEmail, "SECONDARY_PARENT_INVITE", {
    secondary_parent_name: secondaryName || cleanEmail,
    child_name: application.childName,
    school: schoolLabel(application.school),
    round_year: application.academicYear,
    registration_link: `${appUrl}/register?token=${invitationToken}`,
    // E1: the second parent is contributing to an EXISTING application, so
    // {{deadline}} is that application's own effective submission deadline —
    // its override first, else the round default on its type's clock.
    // Previously the 30-day token expiry.
    ...invitationDeadlineFields(
      application.deadlineRound,
      application.applicationType,
      expiresAt,
      application.submissionDeadlineAt
    ),
  });

  if (!emailResult.success) {
    console.error(
      "[invitations] addSecondParentAction email error:",
      emailResult.error
    );

    // Roll back the invitation + contributor and record the failure. The
    // contributor is deleted by the invitation? No — they are independent
    // rows, so delete both explicitly.
    await withAdminContext(async (tx) => {
      await tx.invitation
        .delete({ where: { id: invitationId } })
        .catch((err) => {
          console.error(
            "[invitations] addSecondParentAction invitation rollback failed:",
            err
          );
        });
      await tx.applicationContributor
        .deleteMany({
          where: {
            applicationId: application.id,
            role: ApplicationContributorRole.SECONDARY,
          },
        })
        .catch((err) => {
          console.error(
            "[invitations] addSecondParentAction contributor rollback failed:",
            err
          );
        });
      await createAuditLog(tx, {
        userId: user.id,
        action: AUDIT_ACTIONS.ADD_SECOND_PARENT_FAILED,
        entityType: AUDIT_ENTITY_TYPES.ApplicationContributor,
        entityId: application.id,
        context: `Second-parent invite to ${cleanEmail} rolled back — email failed to send`,
        metadata: {
          email: cleanEmail,
          applicationId: application.id,
          profileId,
          emailError: emailResult.error ?? null,
        },
      });
    }).catch((err) => {
      console.error(
        "[invitations] addSecondParentAction rollback tx failed:",
        err
      );
    });

    await rollbackAuthUser();

    revalidatePath(`/applications/${application.id}`);
    return {
      success: false,
      error: `Email failed to send. The second-parent invite was rolled back — please try again. (${emailResult.error})`,
    };
  }

  revalidatePath(`/applications/${application.id}`);
  return { success: true };
}
