"use server";

/**
 * Server actions for invitation management.
 *
 * Mirrors the hardened staff invite pattern (`inviteStaffAction` in
 * `src/app/(admin)/users/actions.ts`):
 *
 *   1. Validate input.
 *   2. Create Supabase auth user up front with a throwaway password and
 *      `email_confirm: true` so Supabase does not fire its system invite
 *      OTP email.
 *   3. Inside one `withAdminContext(tx)` transaction, upsert the Profile,
 *      create the Invitation row (token auto-generated by the helper) and
 *      write the audit log.
 *   4. On any failure between steps 3a–3c, roll back the auth user so we
 *      never leave an orphan `auth.users` row.
 *   5. Send the branded Resend INVITATION email with the
 *      `?token=<token>` link as the registration URL.
 */

import { randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { InvitationStatus, School } from "@prisma/client";
import { requireRole, Role } from "@/lib/auth/roles";
import {
  createInvitation,
  generateInvitationToken,
  getActiveBursaryHolders,
} from "@/lib/db/queries/invitations";
import { createSupabaseAdminClient } from "@/lib/auth/supabase-admin";
import { createProfile } from "@/lib/auth/create-profile";
import { getAppUrl } from "@/lib/app-url";
import { sendEmail } from "@/lib/email/send";
import { withAdminContext } from "@/lib/db/prisma";
import { createAuditLog } from "@/lib/audit/log";
import { prepopulateReassessment, getPreviousYearApplication } from "@/lib/db/queries/reassessment";

// ---------------------------------------------------------------------------
// Validation schema
// ---------------------------------------------------------------------------

const InvitationSchema = z.object({
  email: z.string().email("A valid email address is required"),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  childName: z.string().optional(),
  school: z.nativeEnum(School).optional(),
  roundId: z.string().uuid("An application round is required"),
});

// ---------------------------------------------------------------------------
// Result type
// ---------------------------------------------------------------------------

export interface InvitationActionResult {
  success: boolean;
  error?: string;
  fieldErrors?: Record<string, string[]>;
}

export interface BatchInviteResult {
  sent: number;
  failed: number;
  errors: string[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Composes a single-line applicant display name from the structured first /
 * last fields, falling back to the empty string.
 */
function composeApplicantName(
  firstName: string | undefined,
  lastName: string | undefined
): string {
  return [firstName, lastName].filter(Boolean).join(" ").trim();
}

function schoolLabel(school: School | undefined | null): string {
  if (!school) return "";
  return school === "TRINITY" ? "Trinity School" : "Whitgift School";
}

// ---------------------------------------------------------------------------
// createInvitationAction (hardened — mirrors inviteStaffAction)
// ---------------------------------------------------------------------------

export async function createInvitationAction(
  formData: FormData
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  const raw = {
    email: formData.get("email") as string,
    firstName: (formData.get("firstName") as string) || undefined,
    lastName: (formData.get("lastName") as string) || undefined,
    childName: (formData.get("childName") as string) || undefined,
    school: (formData.get("school") as string) || undefined,
    roundId: (formData.get("roundId") as string) || undefined,
  };

  const parsed = InvitationSchema.safeParse(raw);
  if (!parsed.success) {
    return {
      success: false,
      fieldErrors: parsed.error.flatten().fieldErrors as Record<string, string[]>,
    };
  }

  const { email, firstName, lastName, childName, school, roundId } =
    parsed.data;

  const effectiveApplicantName = composeApplicantName(firstName, lastName);

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();

  // 1. Create Supabase auth user silently. email_confirm: true suppresses
  //    the built-in OTP email — only the branded Resend message will reach
  //    the applicant.
  const tempPassword = randomBytes(24).toString("base64url");
  const { data: created, error: supabaseError } =
    await supabase.auth.admin.createUser({
      email,
      password: tempPassword,
      email_confirm: true,
      app_metadata: { role: "APPLICANT" },
    });

  if (supabaseError || !created?.user) {
    const message = supabaseError?.message ?? "Failed to create auth user";
    console.error("[invitations] createInvitationAction createUser error:", supabaseError);
    return { success: false, error: message };
  }
  const authUserId = created.user.id;

  // 2. Profile + Invitation + audit log under one admin context. Any throw
  //    rolls back the auth user.
  let invitationId: string;
  let invitationToken: string;
  let academicYear = "";
  try {
    const result = await withAdminContext(async (tx) => {
      const profile = await createProfile(tx, {
        id: authUserId,
        email,
        role: Role.APPLICANT,
        firstName,
        lastName,
      });
      if (!profile.success) {
        return { success: false as const, error: profile.error };
      }

      const inv = await createInvitation(tx, {
        email,
        firstName,
        lastName,
        childName,
        school,
        roundId,
        authUserId,
        createdBy: user.id,
        expiresAt,
      });

      let year = "";
      if (roundId) {
        const round = await tx.round.findUnique({
          where: { id: roundId },
          select: { academicYear: true },
        });
        year = round?.academicYear ?? "";
      }

      await createAuditLog(tx, {
        userId: user.id,
        action: "CREATE_INVITATION",
        entityType: "Invitation",
        entityId: inv.id,
        context: `Sent invitation to ${email}`,
        metadata: {
          email,
          roundId: roundId ?? null,
          authUserId,
        },
      });

      return {
        success: true as const,
        invitationId: inv.id,
        token: inv.token,
        academicYear: year,
      };
    });

    if (!result.success) {
      await supabase.auth.admin.deleteUser(authUserId).catch((err) => {
        console.error(
          "[invitations] createInvitationAction auth rollback failed:",
          err
        );
      });
      return {
        success: false,
        error: result.error ?? "Failed to create invitation",
      };
    }

    invitationId = result.invitationId;
    invitationToken = result.token;
    academicYear = result.academicYear;
  } catch (err) {
    await supabase.auth.admin.deleteUser(authUserId).catch((rollbackErr) => {
      console.error(
        "[invitations] createInvitationAction auth rollback failed:",
        rollbackErr
      );
    });
    const message =
      err instanceof Error ? err.message : "Failed to send invitation";
    console.error("[invitations] createInvitationAction error:", err);
    return { success: false, error: message };
  }

  // 3. Send branded INVITATION email. The email is now inside the rollback
  //    boundary (#5): a send failure would otherwise leave a PENDING orphan
  //    row + auth user that looks valid but whose token never reached the
  //    recipient. On failure we hard-roll-back — delete the invitation row,
  //    delete the auth user, and write a failure audit entry so the attempt
  //    stays visible — then surface a clear error to the admin.
  const emailResult = await sendEmail(email, "INVITATION", {
    applicant_name: effectiveApplicantName || email,
    child_name: childName ?? "",
    school: schoolLabel(school),
    round_year: academicYear,
    registration_link: `${appUrl}/register?token=${invitationToken}`,
    deadline: expiresAt.toLocaleDateString("en-GB"),
  });

  if (!emailResult.success) {
    console.error(
      "[invitations] createInvitationAction email error:",
      emailResult.error
    );

    // Roll back the just-created invitation row and record the failure.
    await withAdminContext(async (tx) => {
      await tx.invitation.delete({ where: { id: invitationId } }).catch((err) => {
        console.error(
          "[invitations] createInvitationAction invitation rollback failed:",
          err
        );
      });
      await createAuditLog(tx, {
        userId: user.id,
        action: "CREATE_INVITATION_FAILED",
        entityType: "Invitation",
        entityId: invitationId,
        context: `Invitation to ${email} rolled back — email failed to send`,
        metadata: {
          email,
          roundId: roundId ?? null,
          authUserId,
          emailError: emailResult.error ?? null,
        },
      });
    }).catch((err) => {
      console.error(
        "[invitations] createInvitationAction rollback tx failed:",
        err
      );
    });

    // Roll back the auth user so we never leave an orphan account behind.
    await supabase.auth.admin.deleteUser(authUserId).catch((err) => {
      console.error(
        "[invitations] createInvitationAction auth rollback failed:",
        err
      );
    });

    revalidatePath("/invitations");
    return {
      success: false,
      error: `Email failed to send. The invitation was rolled back — please try again. (${emailResult.error})`,
    };
  }

  void invitationId; // referenced for type completeness; used by audit log above

  revalidatePath("/invitations");
  return { success: true };
}

// ---------------------------------------------------------------------------
// batchReassessmentInviteAction (hardened — per-row auth-user rollback)
// ---------------------------------------------------------------------------

/**
 * Sends reassessment invitations to all active bursary holders that have not
 * yet been invited for the specified round. Each row is wrapped in its own
 * try/catch so a single failure does not poison the whole batch, and each
 * row gets the same auth-user-up-front + rollback hardening as
 * `createInvitationAction`.
 */
export async function batchReassessmentInviteAction(
  roundId: string
): Promise<BatchInviteResult> {
  const user = await requireRole([Role.ADMIN]);

  const result: BatchInviteResult = { sent: 0, failed: 0, errors: [] };

  let holders: Awaited<ReturnType<typeof getActiveBursaryHolders>> = [];
  let academicYear = "";
  try {
    const loaded = await withAdminContext(async (tx) => {
      const h = await getActiveBursaryHolders(tx, roundId);
      const round = await tx.round.findUnique({
        where: { id: roundId },
        select: { academicYear: true },
      });
      return { holders: h, academicYear: round?.academicYear ?? "" };
    });
    holders = loaded.holders;
    academicYear = loaded.academicYear;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to load bursary holders";
    console.error("[batch-invite] Load error:", err);
    result.errors.push(message);
    return result;
  }

  const supabase = createSupabaseAdminClient();
  const appUrl = getAppUrl();

  for (let i = 0; i < holders.length; i++) {
    const holder = holders[i];
    const { email, firstName, lastName } = holder.leadApplicant;
    const applicantName =
      composeApplicantName(firstName ?? undefined, lastName ?? undefined) ||
      email;

    // Per-row auth-user provisioning.
    let authUserId: string | null = null;
    try {
      const tempPassword = randomBytes(24).toString("base64url");
      const { data: created, error: supabaseError } =
        await supabase.auth.admin.createUser({
          email,
          password: tempPassword,
          email_confirm: true,
          app_metadata: { role: "APPLICANT" },
        });

      if (supabaseError || !created?.user) {
        throw new Error(
          supabaseError?.message ?? "Failed to create auth user"
        );
      }
      authUserId = created.user.id;

      const expiresAt = new Date();
      expiresAt.setDate(expiresAt.getDate() + 30);

      const txResult = await withAdminContext(async (tx) => {
        const profile = await createProfile(tx, {
          id: authUserId!,
          email,
          role: Role.APPLICANT,
          firstName: firstName ?? undefined,
          lastName: lastName ?? undefined,
        });
        if (!profile.success) {
          return { success: false as const, error: profile.error };
        }

        const invitation = await createInvitation(tx, {
          email,
          firstName: firstName ?? undefined,
          lastName: lastName ?? undefined,
          childName: holder.childName,
          school: holder.school,
          roundId,
          bursaryAccountId: holder.id,
          authUserId: authUserId!,
          createdBy: user.id,
          expiresAt,
        });

        await createAuditLog(tx, {
          userId: user.id,
          action: "BATCH_REASSESSMENT_INVITE",
          entityType: "Invitation",
          entityId: invitation.id,
          context: `Sent reassessment invitation to ${email}`,
          metadata: {
            email,
            roundId,
            bursaryAccountId: holder.id,
            authUserId,
          },
        });

        return {
          success: true as const,
          invitationId: invitation.id,
          token: invitation.token,
          expiresAt,
        };
      });

      if (!txResult.success) {
        throw new Error(txResult.error ?? "Failed to create invitation");
      }

      // Send branded reassessment email
      const emailResult = await sendEmail(email, "REASSESSMENT", {
        applicant_name: applicantName,
        child_name: holder.childName,
        school: schoolLabel(holder.school),
        round_year: academicYear,
        registration_link: `${appUrl}/register?token=${txResult.token}`,
        deadline: txResult.expiresAt.toLocaleDateString("en-GB"),
      });

      if (emailResult.success) {
        result.sent++;
      } else {
        result.failed++;
        result.errors.push(`${email}: ${emailResult.error}`);
      }
    } catch (err) {
      // Roll back the auth user if we got that far.
      if (authUserId) {
        await supabase.auth.admin.deleteUser(authUserId).catch((rollbackErr) => {
          console.error(
            `[batch-invite] auth rollback failed for ${email}:`,
            rollbackErr
          );
        });
      }
      const message =
        err instanceof Error ? err.message : "Unknown error";
      result.failed++;
      result.errors.push(`${email}: ${message}`);
      console.error(`[batch-invite] Error for ${email}:`, err);
    }

    // Rate-limit delay between sends (100 ms), skip after last item
    if (i < holders.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }

  revalidatePath("/invitations");
  return result;
}

// ---------------------------------------------------------------------------
// resendInvitationAction
// ---------------------------------------------------------------------------

/**
 * Regenerates the single-use token, resets the 30-day expiry, and re-sends
 * the branded INVITATION email. Only valid on PENDING rows.
 */
export async function resendInvitationAction(
  invitationId: string
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  if (!invitationId || typeof invitationId !== "string") {
    return { success: false, error: "Invalid invitation id." };
  }

  try {
    const invitation = await withAdminContext((tx) =>
      tx.invitation.findUnique({
        where: { id: invitationId },
        include: {
          round: { select: { academicYear: true } },
        },
      })
    );

    if (!invitation) {
      return { success: false, error: "Invitation not found." };
    }

    if (invitation.status !== InvitationStatus.PENDING) {
      return {
        success: false,
        error: "Only pending invitations can be resent.",
      };
    }

    const newToken = generateInvitationToken();
    const newExpiresAt = new Date();
    newExpiresAt.setDate(newExpiresAt.getDate() + 30);

    await withAdminContext(async (tx) => {
      await tx.invitation.update({
        where: { id: invitationId },
        data: {
          token: newToken,
          expiresAt: newExpiresAt,
        },
      });

      await createAuditLog(tx, {
        userId: user.id,
        action: "RESEND_INVITATION",
        entityType: "Invitation",
        entityId: invitationId,
        context: `Resent invitation to ${invitation.email}`,
        metadata: {
          email: invitation.email,
          expiresAt: newExpiresAt.toISOString(),
        },
      });
    });

    const appUrl = getAppUrl();
    const applicantName =
      composeApplicantName(
        invitation.firstName ?? undefined,
        invitation.lastName ?? undefined
      ) || invitation.email;

    const emailResult = await sendEmail(invitation.email, "INVITATION", {
      applicant_name: applicantName,
      child_name: invitation.childName ?? "",
      school: schoolLabel(invitation.school),
      round_year: invitation.round?.academicYear ?? "",
      registration_link: `${appUrl}/register?token=${newToken}`,
      deadline: newExpiresAt.toLocaleDateString("en-GB"),
    });

    if (!emailResult.success) {
      console.error(
        "[invitations] resendInvitationAction email error:",
        emailResult.error
      );
      return {
        success: false,
        error: `Token refreshed but email failed to send: ${emailResult.error}`,
      };
    }

    revalidatePath("/invitations");
    return { success: true };
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to resend invitation";
    console.error("[invitations] resendInvitationAction error:", err);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// revokeInvitationAction
// ---------------------------------------------------------------------------

/**
 * Marks a PENDING invitation as EXPIRED. If the invitation was never accepted
 * and we provisioned a Supabase auth user up front, soft-delete that auth
 * user so we don't leave a half-onboarded account behind.
 */
export async function revokeInvitationAction(
  invitationId: string
): Promise<InvitationActionResult> {
  const user = await requireRole([Role.ADMIN]);

  if (!invitationId || typeof invitationId !== "string") {
    return { success: false, error: "Invalid invitation id." };
  }

  try {
    const invitation = await withAdminContext((tx) =>
      tx.invitation.findUnique({ where: { id: invitationId } })
    );

    if (!invitation) {
      return { success: false, error: "Invitation not found." };
    }

    if (invitation.status !== InvitationStatus.PENDING) {
      return {
        success: false,
        error: "Only pending invitations can be revoked.",
      };
    }

    const shouldDeleteAuthUser =
      invitation.authUserId !== null && invitation.acceptedAt === null;

    await withAdminContext(async (tx) => {
      await tx.invitation.update({
        where: { id: invitationId },
        data: { status: InvitationStatus.EXPIRED },
      });

      await createAuditLog(tx, {
        userId: user.id,
        action: "REVOKE_INVITATION",
        entityType: "Invitation",
        entityId: invitationId,
        context: `Revoked invitation to ${invitation.email}`,
        metadata: {
          email: invitation.email,
          authUserId: invitation.authUserId,
          authUserDeleted: shouldDeleteAuthUser,
        },
      });
    });

    if (shouldDeleteAuthUser && invitation.authUserId) {
      const supabase = createSupabaseAdminClient();
      const { error: deleteError } = await supabase.auth.admin.deleteUser(
        invitation.authUserId
      );
      if (deleteError) {
        console.error(
          "[invitations] revokeInvitationAction auth deletion warning:",
          deleteError
        );
      }
    }

    revalidatePath("/invitations");
    return { success: true };
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to revoke invitation";
    console.error("[invitations] revokeInvitationAction error:", err);
    return { success: false, error: message };
  }
}

// ---------------------------------------------------------------------------
// createReassessmentApplicationAction
// ---------------------------------------------------------------------------

const ReassessmentApplicationSchema = z.object({
  bursaryAccountId: z.string().uuid("A valid bursary account ID is required"),
  roundId: z.string().uuid("A valid round ID is required"),
});

export interface ReassessmentApplicationResult {
  success: boolean;
  applicationId?: string;
  error?: string;
}

/**
 * Creates a re-assessment application and pre-populates it with personal
 * section data from the previous year.
 *
 * Called after an applicant registers via a re-assessment invitation.
 * Links the application to the existing BursaryAccount with isReassessment: true.
 */
export async function createReassessmentApplicationAction(
  bursaryAccountId: string,
  roundId: string
): Promise<ReassessmentApplicationResult> {
  await requireRole([Role.ADMIN]);

  const parsed = ReassessmentApplicationSchema.safeParse({
    bursaryAccountId,
    roundId,
  });
  if (!parsed.success) {
    return {
      success: false,
      error: parsed.error.issues.map((i) => i.message).join("; "),
    };
  }

  try {
    const result = await withAdminContext(async (tx) => {
      // Load bursary account details
      const account = await tx.bursaryAccount.findUnique({
        where: { id: bursaryAccountId },
        include: { leadApplicant: true },
      });

      if (!account) {
        return { success: false as const, error: "Bursary account not found." };
      }

      // Generate reference
      const reference = `REA-${account.reference}-${roundId.slice(0, 8).toUpperCase()}`;

      // Create the re-assessment application
      const application = await tx.application.create({
        data: {
          reference,
          roundId,
          bursaryAccountId,
          leadApplicantId: account.leadApplicantId,
          school: account.school,
          childName: account.childName,
          childDob: account.childDob,
          entryYear: account.entryYear,
          entryYearGroup: account.entryYearGroup,
          isReassessment: true,
          status: "PRE_SUBMISSION",
        },
      });

      // Pre-populate from the most recent previous year application
      const previous = await getPreviousYearApplication(tx, bursaryAccountId, roundId);
      if (previous) {
        await prepopulateReassessment(tx, application.id, previous.id);
      }

      await createAuditLog(tx, {
        action: "CREATE_REASSESSMENT_APPLICATION",
        entityType: "Application",
        entityId: application.id,
        context: `Re-assessment application created for ${account.childName}`,
        metadata: {
          bursaryAccountId,
          roundId,
          previousApplicationId: previous?.id ?? null,
        },
      });

      return { success: true as const, applicationId: application.id };
    });

    if (!result.success) return result;
    revalidatePath("/admin/applications");
    return result;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to create re-assessment application";
    console.error("[createReassessmentApplicationAction] error:", err);
    return { success: false, error: message };
  }
}
