/**
 * Multi-round account history loader — Epic 05 (plan §3.4, §5.2).
 *
 * Lists every application for the signed-in lead applicant across rounds (the
 * account spine is BursaryAccount, but applications are keyed by
 * `leadApplicantId` so we list those directly), newest first, each with a
 * parent-safe status + submitted date. Submitted entries expose a preserved
 * read-only PDF; prior years are reference-only and never re-open as editable
 * forms.
 *
 * Also surfaces the upcoming-rounds lineup for active recipients. The forward
 * schedule itself is Epic 10 — until then this returns an empty list and the
 * page shows a neutral "no upcoming rounds scheduled yet" state.
 *
 * Server-only.
 */

import "server-only";

import { withUserContext, type RlsRole } from "@/lib/db/prisma";
import {
  projectParentStatus,
  type ParentStatusProjection,
} from "@/lib/portal/status-projection";

export interface HistoryEntry {
  id: string;
  reference: string;
  academicYear: string;
  childName: string | null;
  isDraft: boolean;
  submittedAt: Date | null;
  status: ParentStatusProjection;
}

export interface UpcomingRound {
  id: string;
  academicYear: string;
}

export interface AccountHistory {
  entries: HistoryEntry[];
  /** True when the lead applicant has at least one ACTIVE bursary account. */
  hasActiveBursary: boolean;
  /** Upcoming rounds the account is scheduled into (Epic 10 — empty until then). */
  upcoming: UpcomingRound[];
}

interface Caller {
  id: string;
  role: RlsRole;
}

export async function loadAccountHistory(
  caller: Caller
): Promise<AccountHistory> {
  return withUserContext(caller.id, caller.role, async (tx) => {
    const applications = await tx.application.findMany({
      where: { leadApplicantId: caller.id },
      orderBy: [{ submittedAt: "desc" }, { createdAt: "desc" }],
      select: {
        id: true,
        reference: true,
        childName: true,
        formStatus: true,
        applicationType: true,
        submittedAt: true,
        round: { select: { academicYear: true } },
        assessment: { select: { status: true, outcome: true } },
      },
    });

    const entries: HistoryEntry[] = applications.map((app) => ({
      id: app.id,
      reference: app.reference,
      academicYear: app.round.academicYear,
      childName: app.childName,
      isDraft: app.formStatus !== "SUBMITTED",
      submittedAt: app.submittedAt,
      status: projectParentStatus({
        formStatus: app.formStatus,
        applicationType: app.applicationType,
        assessmentStatus: app.assessment?.status ?? null,
        outcome: app.assessment?.outcome ?? null,
      }),
    }));

    const activeAccounts = await tx.bursaryAccount.count({
      where: { leadApplicantId: caller.id, status: "ACTIVE" },
    });

    // Upcoming-rounds lineup: generated by Epic 10. Until then there is no
    // forward schedule to read, so the lineup is intentionally empty and the
    // page renders a neutral empty state.
    const upcoming: UpcomingRound[] = [];

    return {
      entries,
      hasActiveBursary: activeAccounts > 0,
      upcoming,
    };
  });
}
