-- CH-43 follow-up — seed the postcode_areas rows.
--
-- 20260825220000_ch43_postcode_areas created the table but shipped it EMPTY:
-- the 94 rows lived only in `seed-reference.ts`, which is run by hand per
-- environment. So the lookup silently resolved every district to the OTHER
-- fallback until someone remembered to run the seed — the exact failure mode the
-- CH-38/39 migration was written to avoid. That migration is already applied, so
-- per the migration discipline it is left alone and this follows it.
--
-- `seed-reference.ts` remains the source of truth for a fresh database; this
-- brings existing databases to the same state automatically. Idempotent via
-- ON CONFLICT on the unique district, and it refreshes `area` so a correction to
-- her table lands on re-run rather than being skipped.

INSERT INTO "postcode_areas" ("id", "district", "area")
VALUES
  (gen_random_uuid(), 'CR0', 'CROYDON'),
  (gen_random_uuid(), 'CR2', 'SOUTH CROYDON'),
  (gen_random_uuid(), 'CR3', 'CATERHAM / WHYTELEAFE'),
  (gen_random_uuid(), 'CR4', 'MITCHAM'),
  (gen_random_uuid(), 'CR5', 'COULSDON'),
  (gen_random_uuid(), 'CR6', 'WARLINGHAM'),
  (gen_random_uuid(), 'CR7', 'THORNTON HEATH'),
  (gen_random_uuid(), 'CR8', 'PURLEY / KENLEY'),
  (gen_random_uuid(), 'KT1', 'KINGSTON UPON THAMES'),
  (gen_random_uuid(), 'KT2', 'KINGSTON UPON THAMES'),
  (gen_random_uuid(), 'KT3', 'NEW MALDEN'),
  (gen_random_uuid(), 'KT4', 'WORCESTER PARK'),
  (gen_random_uuid(), 'KT5', 'SURBITON'),
  (gen_random_uuid(), 'KT6', 'SURBITON'),
  (gen_random_uuid(), 'KT7', 'THAMES DITTON'),
  (gen_random_uuid(), 'KT8', 'EAST MOLESEY; WEST MOLESEY'),
  (gen_random_uuid(), 'KT9', 'CHESSINGTON'),
  (gen_random_uuid(), 'KT10', 'ESHER'),
  (gen_random_uuid(), 'KT11', 'COBHAM'),
  (gen_random_uuid(), 'KT12', 'WALTON-ON-THAMES'),
  (gen_random_uuid(), 'KT13', 'WEYBRIDGE'),
  (gen_random_uuid(), 'KT14', 'WEST BYFLEET'),
  (gen_random_uuid(), 'KT15', 'ADDLESTONE'),
  (gen_random_uuid(), 'KT16', 'CHERTSEY'),
  (gen_random_uuid(), 'KT17', 'EPSOM'),
  (gen_random_uuid(), 'KT18', 'EPSOM'),
  (gen_random_uuid(), 'KT19', 'EPSOM'),
  (gen_random_uuid(), 'KT20', 'TADWORTH'),
  (gen_random_uuid(), 'KT21', 'ASHTEAD'),
  (gen_random_uuid(), 'KT22', 'LEATHERHEAD'),
  (gen_random_uuid(), 'KT23', 'LEATHERHEAD'),
  (gen_random_uuid(), 'KT24', 'LEATHERHEAD'),
  (gen_random_uuid(), 'SM1', 'SUTTON'),
  (gen_random_uuid(), 'SM2', 'SUTTON'),
  (gen_random_uuid(), 'SM3', 'SUTTON'),
  (gen_random_uuid(), 'SM4', 'MORDEN'),
  (gen_random_uuid(), 'SM5', 'CARSHALTON'),
  (gen_random_uuid(), 'SM6', 'WALLINGTON'),
  (gen_random_uuid(), 'SM7', 'BANSTEAD'),
  (gen_random_uuid(), 'SE1', 'LAMBETH'),
  (gen_random_uuid(), 'SE2', 'ABBEY WOOD'),
  (gen_random_uuid(), 'SE3', 'BLACKHEATH'),
  (gen_random_uuid(), 'SE4', 'BROCKLEY'),
  (gen_random_uuid(), 'SE5', 'CAMBERWELL'),
  (gen_random_uuid(), 'SE6', 'CATFORD'),
  (gen_random_uuid(), 'SE7', 'CHARLTON'),
  (gen_random_uuid(), 'SE8', 'DEPFORD'),
  (gen_random_uuid(), 'SE9', 'ELTHAM'),
  (gen_random_uuid(), 'SE10', 'GREENWICH'),
  (gen_random_uuid(), 'SE11', 'KENNINGTON'),
  (gen_random_uuid(), 'SE12', 'LEE'),
  (gen_random_uuid(), 'SE13', 'LEWISHAM'),
  (gen_random_uuid(), 'SE14', 'NEW CROSS'),
  (gen_random_uuid(), 'SE15', 'PECKHAM'),
  (gen_random_uuid(), 'SE16', 'ROTHERHITHE'),
  (gen_random_uuid(), 'SE17', 'WALWORTH'),
  (gen_random_uuid(), 'SE18', 'WOOLWICH'),
  (gen_random_uuid(), 'SE19', 'NORWOOD'),
  (gen_random_uuid(), 'SE20', 'ANERLEY'),
  (gen_random_uuid(), 'SE21', 'DULWICH'),
  (gen_random_uuid(), 'SE22', 'EAST DULWICH'),
  (gen_random_uuid(), 'SE23', 'FOREST HILL'),
  (gen_random_uuid(), 'SE24', 'HERNE HILL'),
  (gen_random_uuid(), 'SE25', 'SOUTH NORWOOD'),
  (gen_random_uuid(), 'SE26', 'SYDENHAM'),
  (gen_random_uuid(), 'SE27', 'WEST NORWOOD'),
  (gen_random_uuid(), 'SW1', 'LONDON'),
  (gen_random_uuid(), 'SW2', 'BRIXTON'),
  (gen_random_uuid(), 'SW3', 'CHELSEA'),
  (gen_random_uuid(), 'SW4', 'CLAPHAM'),
  (gen_random_uuid(), 'SW5', 'EARLS COURT'),
  (gen_random_uuid(), 'SW6', 'FULHAM'),
  (gen_random_uuid(), 'SW7', 'SOUTH KENSINGTON'),
  (gen_random_uuid(), 'SW8', 'SOUTH LAMBETH'),
  (gen_random_uuid(), 'SW9', 'STOCKWELL'),
  (gen_random_uuid(), 'SW10', 'BROMPTON'),
  (gen_random_uuid(), 'SW11', 'BATTERSEA'),
  (gen_random_uuid(), 'SW12', 'BALHAM'),
  (gen_random_uuid(), 'SW13', 'BARNES'),
  (gen_random_uuid(), 'SW14', 'MORTLAKE'),
  (gen_random_uuid(), 'SW15', 'PUTNEY'),
  (gen_random_uuid(), 'SW16', 'STREATHAM'),
  (gen_random_uuid(), 'SW17', 'TOOTING'),
  (gen_random_uuid(), 'SW18', 'WANDSWORTH'),
  (gen_random_uuid(), 'SW19', 'WIMBLEDON'),
  (gen_random_uuid(), 'SW20', 'WIMBLEDON'),
  (gen_random_uuid(), 'BR1', 'BROMLEY'),
  (gen_random_uuid(), 'BR2', 'KESTON'),
  (gen_random_uuid(), 'BR3', 'BECKENHAM'),
  (gen_random_uuid(), 'BR4', 'WEST WICKHAM'),
  (gen_random_uuid(), 'BR5', 'ORPINGTON'),
  (gen_random_uuid(), 'BR6', 'ORPINGTON'),
  (gen_random_uuid(), 'BR7', 'CHISLEHURST'),
  (gen_random_uuid(), 'BR8', 'SWANLEY')
ON CONFLICT ("district") DO UPDATE SET "area" = EXCLUDED."area";
