/**
 * CH-43 — Charlotte's postcode district → area lookup, transcribed from
 * `POST CODE - POST CODE AREA.xlsx` (attached to her 24 Aug 2026 email).
 *
 * She wants the assessor to type the outward code and the summary to read the
 * two joined: *"the assessor types : SM4, and the field within the summary view
 * below reports : SM4-MORDEN"*.
 *
 * Her sheet ends with a `*** | OTHER` catch-all row. That is not a district, so
 * it is not seeded — it is the FALLBACK, implemented in `resolvePostcodeArea`:
 * a district she has not listed resolves to "OTHER" rather than being rejected.
 * Her list is Croydon-and-surrounds, so an applicant from further afield is
 * expected, not an error.
 *
 * `CR0***` in her sheet carries a footnote marker, not a different district —
 * the asterisks are stripped, giving `CR0`.
 */
export const POSTCODE_AREA_FALLBACK = "OTHER";

export const postcodeAreas: ReadonlyArray<{ district: string; area: string }> = [
  { district: "CR0", area: "CROYDON" },
  { district: "CR2", area: "SOUTH CROYDON" },
  { district: "CR3", area: "CATERHAM / WHYTELEAFE" },
  { district: "CR4", area: "MITCHAM" },
  { district: "CR5", area: "COULSDON" },
  { district: "CR6", area: "WARLINGHAM" },
  { district: "CR7", area: "THORNTON HEATH" },
  { district: "CR8", area: "PURLEY / KENLEY" },
  { district: "KT1", area: "KINGSTON UPON THAMES" },
  { district: "KT2", area: "KINGSTON UPON THAMES" },
  { district: "KT3", area: "NEW MALDEN" },
  { district: "KT4", area: "WORCESTER PARK" },
  { district: "KT5", area: "SURBITON" },
  { district: "KT6", area: "SURBITON" },
  { district: "KT7", area: "THAMES DITTON" },
  { district: "KT8", area: "EAST MOLESEY; WEST MOLESEY" },
  { district: "KT9", area: "CHESSINGTON" },
  { district: "KT10", area: "ESHER" },
  { district: "KT11", area: "COBHAM" },
  { district: "KT12", area: "WALTON-ON-THAMES" },
  { district: "KT13", area: "WEYBRIDGE" },
  { district: "KT14", area: "WEST BYFLEET" },
  { district: "KT15", area: "ADDLESTONE" },
  { district: "KT16", area: "CHERTSEY" },
  { district: "KT17", area: "EPSOM" },
  { district: "KT18", area: "EPSOM" },
  { district: "KT19", area: "EPSOM" },
  { district: "KT20", area: "TADWORTH" },
  { district: "KT21", area: "ASHTEAD" },
  { district: "KT22", area: "LEATHERHEAD" },
  { district: "KT23", area: "LEATHERHEAD" },
  { district: "KT24", area: "LEATHERHEAD" },
  { district: "SM1", area: "SUTTON" },
  { district: "SM2", area: "SUTTON" },
  { district: "SM3", area: "SUTTON" },
  { district: "SM4", area: "MORDEN" },
  { district: "SM5", area: "CARSHALTON" },
  { district: "SM6", area: "WALLINGTON" },
  { district: "SM7", area: "BANSTEAD" },
  { district: "SE1", area: "LAMBETH" },
  { district: "SE2", area: "ABBEY WOOD" },
  { district: "SE3", area: "BLACKHEATH" },
  { district: "SE4", area: "BROCKLEY" },
  { district: "SE5", area: "CAMBERWELL" },
  { district: "SE6", area: "CATFORD" },
  { district: "SE7", area: "CHARLTON" },
  { district: "SE8", area: "DEPFORD" },
  { district: "SE9", area: "ELTHAM" },
  { district: "SE10", area: "GREENWICH" },
  { district: "SE11", area: "KENNINGTON" },
  { district: "SE12", area: "LEE" },
  { district: "SE13", area: "LEWISHAM" },
  { district: "SE14", area: "NEW CROSS" },
  { district: "SE15", area: "PECKHAM" },
  { district: "SE16", area: "ROTHERHITHE" },
  { district: "SE17", area: "WALWORTH" },
  { district: "SE18", area: "WOOLWICH" },
  { district: "SE19", area: "NORWOOD" },
  { district: "SE20", area: "ANERLEY" },
  { district: "SE21", area: "DULWICH" },
  { district: "SE22", area: "EAST DULWICH" },
  { district: "SE23", area: "FOREST HILL" },
  { district: "SE24", area: "HERNE HILL" },
  { district: "SE25", area: "SOUTH NORWOOD" },
  { district: "SE26", area: "SYDENHAM" },
  { district: "SE27", area: "WEST NORWOOD" },
  { district: "SW1", area: "LONDON" },
  { district: "SW2", area: "BRIXTON" },
  { district: "SW3", area: "CHELSEA" },
  { district: "SW4", area: "CLAPHAM" },
  { district: "SW5", area: "EARLS COURT" },
  { district: "SW6", area: "FULHAM" },
  { district: "SW7", area: "SOUTH KENSINGTON" },
  { district: "SW8", area: "SOUTH LAMBETH" },
  { district: "SW9", area: "STOCKWELL" },
  { district: "SW10", area: "BROMPTON" },
  { district: "SW11", area: "BATTERSEA" },
  { district: "SW12", area: "BALHAM" },
  { district: "SW13", area: "BARNES" },
  { district: "SW14", area: "MORTLAKE" },
  { district: "SW15", area: "PUTNEY" },
  { district: "SW16", area: "STREATHAM" },
  { district: "SW17", area: "TOOTING" },
  { district: "SW18", area: "WANDSWORTH" },
  { district: "SW19", area: "WIMBLEDON" },
  { district: "SW20", area: "WIMBLEDON" },
  { district: "BR1", area: "BROMLEY" },
  { district: "BR2", area: "KESTON" },
  { district: "BR3", area: "BECKENHAM" },
  { district: "BR4", area: "WEST WICKHAM" },
  { district: "BR5", area: "ORPINGTON" },
  { district: "BR6", area: "ORPINGTON" },
  { district: "BR7", area: "CHISLEHURST" },
  { district: "BR8", area: "SWANLEY" },
];
