// prisma/seed-data/reason-codes.ts
// All 35 reason codes for year-on-year circumstance changes

export const reasonCodes = [
  { code: 1,  label: "No real change in circumstances",     sortOrder: 1  },
  { code: 2,  label: "Property value increased",             sortOrder: 2  },
  { code: 3,  label: "Salary increase",                      sortOrder: 3  },
  { code: 4,  label: "New employment",                       sortOrder: 4  },
  { code: 5,  label: "Additional income source",             sortOrder: 5  },
  { code: 6,  label: "Savings increased",                    sortOrder: 6  },
  { code: 7,  label: "Investment returns",                   sortOrder: 7  },
  { code: 8,  label: "Rental income increase",               sortOrder: 8  },
  { code: 9,  label: "Pension increase",                     sortOrder: 9  },
  { code: 10, label: "Benefits increase",                    sortOrder: 10 },
  { code: 11, label: "Debt reduced",                         sortOrder: 11 },
  { code: 12, label: "Mortgage paid off",                    sortOrder: 12 },
  { code: 13, label: "Property sold (profit)",               sortOrder: 13 },
  { code: 14, label: "Inheritance received",                 sortOrder: 14 },
  { code: 15, label: "Business growth",                      sortOrder: 15 },
  { code: 16, label: "Bonus/commission received",            sortOrder: 16 },
  { code: 17, label: "Partner started working",              sortOrder: 17 },
  { code: 18, label: "Child left household",                 sortOrder: 18 },
  { code: 19, label: "Salary decrease",                      sortOrder: 19 },
  { code: 20, label: "Job loss/redundancy",                  sortOrder: 20 },
  { code: 21, label: "Business decline",                     sortOrder: 21 },
  { code: 22, label: "Separation/divorce",                   sortOrder: 22 },
  { code: 23, label: "Bereavement",                          sortOrder: 23 },
  { code: 24, label: "New dependent",                        sortOrder: 24 },
  { code: 25, label: "Medical costs increased",              sortOrder: 25 },
  { code: 26, label: "Debt increased",                       sortOrder: 26 },
  { code: 27, label: "Property value decreased",             sortOrder: 27 },
  { code: 28, label: "Savings depleted",                     sortOrder: 28 },
  { code: 29, label: "Investment losses",                    sortOrder: 29 },
  { code: 30, label: "Rental income decrease",               sortOrder: 30 },
  { code: 31, label: "Pension decrease",                     sortOrder: 31 },
  { code: 32, label: "Benefits decrease",                    sortOrder: 32 },
  { code: 33, label: "Partner stopped working",              sortOrder: 33 },
  { code: 34, label: "Additional child joined household",    sortOrder: 34 },
  { code: 35, label: "Stopped qualifying for benefits",      sortOrder: 35 },
] as const;
